<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="UTF-8">
		<title>Home</title>
		<link href='//fonts.googleapis.com/css?family=Lato:300' rel="stylesheet" type="text/css">
		<style>
			body{
				margin: 50px 0px 0px 0px;
				padding: 0px;
				width: 100%;
				font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
				color: #aaa;
				font-size: 18px;
			}
			h1{
				color: #719e40;
				letter-spacing: -3px;
				font-family: 'Lato', sans-serif;
				font-size: 100px;
				font-weight: 200;
				margin-bottom: 0px;
			}
		</style>
	</head>
	<body>
		<h1>Slim</h1>
		<?php if (isset($name)) : ?>
			<h2>Hello <?php echo htmlspecialchars($name); ?>! </h2>
		<?php else: ?>
            <p>Try <a href="http://www.slimframework.com/">SlimFramework</a></p>
		<?php endif; ?>
	</body>
</html>
