CREATE TABLE `ANICOD` (
    `ANICODANC` int(9) NOT NULL COMMENT 'ANIMAL',
    `ANICODCOC` int(9) NOT NULL COMMENT 'ANIMAL COMPRA',
    `ANICODAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
    `ANICODAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
    `ANICODAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
    `ANICODAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ANIMAL COMPRA DETALLE';

CREATE TABLE `ANICODA` (
    `ANICODACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `ANICODAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `ANICODAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
    `ANICODAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `ANICODAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `ANICODADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `ANICODAANCOLD` int(9) NULL COMMENT 'ANIMAL OLD',
    `ANICODACOCOLD` int(9) NULL COMMENT 'ANIMAL COMPRA OLD',

    `ANICODAANCNEW` int(9) NULL COMMENT 'ANIMAL NEW',
    `ANICODACOCNEW` int(9) NULL COMMENT 'ANIMAL COMPRA NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ANIMAL COMPRA DETALLE AUDITORÍA';

ALTER TABLE `ANICOD` ADD PRIMARY KEY (`ANICODCOC`, `ANICODANC`);

ALTER TABLE `ANICOD` ADD KEY `ANICODCOC` (`ANICODCOC`);
ALTER TABLE `ANICOD` ADD CONSTRAINT `FK_ANICODCOC` FOREIGN KEY (`ANICODCOC`) REFERENCES `mayordomo_establecimiento`.`ANICOD` (`ANICODCOD`);

ALTER TABLE `ANICOD` ADD KEY `ANICODANC` (`ANICODANC`);
ALTER TABLE `ANICOD` ADD CONSTRAINT `FK_ANICODANC` FOREIGN KEY (`ANICODANC`) REFERENCES `mayordomo_establecimiento`.`ANIFIC` (`ANIFICCOD`);

ALTER TABLE `ANICODA` ADD PRIMARY KEY (`ANICODACOD`);
ALTER TABLE `ANICODA` MODIFY `ANICODACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `ANICODDLT`
  BEFORE DELETE ON `ANICOD`
  FOR EACH ROW
    INSERT INTO `ANICODA` (`ANICODAMET`, `ANICODAEMP`, `ANICODAUSU`, `ANICODAFEC`, `ANICODADIP`, `ANICODAANCOLD`, `ANICODACOCOLD`)
    VALUES ('DELETE', OLD.`ANICODAEM`, OLD.`ANICODAUS`, NOW(), OLD.`ANICODAIP`, OLD.`ANICODANC`, OLD.`ANICODCOC`);

CREATE TRIGGER `ANICODINS`
  AFTER INSERT ON `ANICOD`
  FOR EACH ROW
    INSERT INTO `ANICODA` (`ANICODAMET`, `ANICODAEMP`, `ANICODAUSU`, `ANICODAFEC`, `ANICODADIP`, `ANICODAANCNEW`, `ANICODACOCNEW`)
    VALUES ('INSERT', NEW.`ANICODAEM`, NEW.`ANICODAUS`, NOW(), NEW.`ANICODAIP`, NEW.`ANICODANC`, NEW.`ANICODCOC`);

CREATE TRIGGER `ANICODUPD`
  AFTER UPDATE ON `ANICOD`
  FOR EACH ROW
    INSERT INTO `ANICODA` (`ANICODAMET`, `ANICODAEMP`, `ANICODAUSU`, `ANICODAFEC`, `ANICODADIP`, `ANICODAANCOLD`, `ANICODACOCOLD`, `ANICODAANCNEW`, `ANICODACOCNEW`)
    VALUES ('UPDATE', NEW.`ANICODAEM`, NEW.`ANICODAUS`, NOW(), NEW.`ANICODAIP`, OLD.`ANICODANC`, OLD.`ANICODCOC`, NEW.`ANICODANC`, NEW.`ANICODCOC`);