CREATE TABLE `ANICOC` (
    `ANICOCCOD` int(9) NOT NULL COMMENT 'CÓDIGO',
    `ANICOCCHO` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'CHOFER',
    `ANICOCCHA` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'CHAPA CAMION',
    `ANICOCENT` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ENTREGADO POR',
    `ANICOCREC` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'RECIBIDO POR',
    `ANICOCCOT` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'COTA',
    `ANICOCPES` decimal(10, 3) NULL COMMENT 'PESO',
    `ANICOCFEC` date NOT NULL COMMENT 'FECHA',
    `ANICOCOBS` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN',
    `ANICOCAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
    `ANICOCAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
    `ANICOCAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
    `ANICOCAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ANIMAL COMPRA CABECERA';

CREATE TABLE `ANICOCA` (
    `ANICOCACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `ANICOCAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `ANICOCAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
    `ANICOCAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `ANICOCAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `ANICOCADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `ANICOCACODOLD` int(9) NULL COMMENT 'CÓDIGO OLD',
    `ANICOCACHOOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CHOFER OLD',
    `ANICOCACHAOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CHAPA CAMION OLD',
    `ANICOCAENTOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'ENTREGADO POR OLD',
    `ANICOCARECOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'RECIBIDO POR OLD',
    `ANICOCACOTOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'COTA OLD',
    `ANICOCAPESOLD` decimal(10, 3) NULL COMMENT 'PESO OLD',
    `ANICOCAFECOLD` date NULL COMMENT 'FECHA OLD',
    `ANICOCAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN OLD',

    `ANICOCACODNEW` int(9) NULL COMMENT 'CÓDIGO NEW',
    `ANICOCACHONEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CHOFER NEW',
    `ANICOCACHANEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CHAPA CAMION NEW',
    `ANICOCAENTNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'ENTREGADO POR NEW',
    `ANICOCARECNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'RECIBIDO POR NEW',
    `ANICOCACOTNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'COTA NEW',
    `ANICOCAPESNEW` decimal(10, 3) NULL COMMENT 'PESO NEW',
    `ANICOCAFECNEW` date NULL COMMENT 'FECHA NEW',
    `ANICOCAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN NEW',
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ANIMAL COMPRA CABECERA AUDITORÍA';

ALTER TABLE `ANICOC` ADD PRIMARY KEY (`ANICOCCOD`);
ALTER TABLE `ANICOC` MODIFY `ANICOCCOD` int(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `ANICOCA` ADD PRIMARY KEY (`ANICOCACOD`);
ALTER TABLE `ANICOCA` MODIFY `ANICOCACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `ANICOCDLT`
  BEFORE DELETE ON `ANICOC`
  FOR EACH ROW
    INSERT INTO `ANICOCA` (`ANICOCAMET`, `ANICOCAEMP`, `ANICOCAUSU`, `ANICOCAFEC`, `ANICOCADIP`, `ANICOCACODOLD`, `ANICOCACHOOLD`, `ANICOCACHAOLD`, `ANICOCAENTOLD`, `ANICOCARECOLD`, `ANICOCACOTOLD`, `ANICOCAPESOLD`, `ANICOCAFECOLD`, `ANICOCAOBSOLD`)
    VALUES ('DELETE', OLD.`ANICOCAEM`, OLD.`ANICOCAUS`, NOW(), OLD.`ANICOCAIP`, OLD.`ANICOCCOD`, OLD.`ANICOCCHO`, OLD.`ANICOCCHA`, OLD.`ANICOCENT`, OLD.`ANICOCREC`, OLD.`ANICOCCOT`, OLD.`ANICOCPES`, OLD.`ANICOCFEC`, OLD.`ANICOCOBS`);

CREATE TRIGGER `ANICOCINS`
  AFTER INSERT ON `ANICOC`
  FOR EACH ROW
    INSERT INTO `ANICOCA` (`ANICOCAMET`, `ANICOCAEMP`, `ANICOCAUSU`, `ANICOCAFEC`, `ANICOCADIP`, `ANICOCACODNEW`, `ANICOCACHONEW`, `ANICOCACHANEW`, `ANICOCAENTNEW`, `ANICOCARECNEW`, `ANICOCACOTNEW`, `ANICOCAPESNEW`, `ANICOCAFECNEW`, `ANICOCAOBSNEW`)
    VALUES ('INSERT', NEW.`ANICOCAEM`, NEW.`ANICOCAUS`, NOW(), NEW.`ANICOCAIP`, NEW.`ANICOCCOD`, NEW.`ANICOCCHO`, NEW.`ANICOCCHA`, NEW.`ANICOCENT`, NEW.`ANICOCREC`, NEW.`ANICOCCOT`, NEW.`ANICOCPES`, NEW.`ANICOCFEC`, NEW.`ANICOCOBS`);

CREATE TRIGGER `ANICOCUPD`
  AFTER UPDATE ON `ANICOC`
  FOR EACH ROW
    INSERT INTO `ANICOCA` (`ANICOCAMET`, `ANICOCAEMP`, `ANICOCAUSU`, `ANICOCAFEC`, `ANICOCADIP`, `ANICOCACODOLD`, `ANICOCACHOOLD`, `ANICOCACHAOLD`, `ANICOCAENTOLD`, `ANICOCARECOLD`, `ANICOCACOTOLD`, `ANICOCAPESOLD`, `ANICOCAFECOLD`, `ANICOCAOBSOLD`, `ANICOCACODNEW`, `ANICOCACHONEW`, `ANICOCACHANEW`, `ANICOCAENTNEW`, `ANICOCARECNEW`, `ANICOCACOTNEW`, `ANICOCAPESNEW`, `ANICOCAFECNEW`, `ANICOCAOBSNEW`)
    VALUES ('UPDATE', NEW.`ANICOCAEM`, NEW.`ANICOCAUS`, NOW(), NEW.`ANICOCAIP`, OLD.`ANICOCCOD`, OLD.`ANICOCCHO`, OLD.`ANICOCCHA`, OLD.`ANICOCENT`, OLD.`ANICOCREC`, OLD.`ANICOCCOT`, OLD.`ANICOCPES`, OLD.`ANICOCFEC`, OLD.`ANICOCOBS`, NEW.`ANICOCCOD`, NEW.`ANICOCCHO`, NEW.`ANICOCCHA`, NEW.`ANICOCENT`, NEW.`ANICOCREC`, NEW.`ANICOCCOT`, NEW.`ANICOCPES`, NEW.`ANICOCFEC`, NEW.`ANICOCOBS`);