CREATE TABLE `ANIDON` (
    `ANIDONCOD` int(9) NOT NULL COMMENT 'CÓDIGO',
    `ANIDONTDC` int(9) NOT NULL COMMENT 'DONACION',
    `ANIDONESC` int(9) NOT NULL COMMENT 'ESTABLECIMIENTO',
    `ANIDONANC` int(9) NOT NULL COMMENT 'ANIMAL',
    `ANIDONFEC` date NOT NULL COMMENT 'FECHA',
    `ANIDONOBS` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN',
    `ANIDONAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
    `ANIDONAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
    `ANIDONAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
    `ANIDONAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ANIMAL DONACION';

CREATE TABLE `ANIDONA` (
    `ANIDONACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `ANIDONAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `ANIDONAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
    `ANIDONAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `ANIDONAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `ANIDONADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `ANIDONACODOLD` int(9) NULL COMMENT 'CÓDIGO OLD',
    `ANIDONATDCOLD` int(9) NULL COMMENT 'DONACION OLD',
    `ANIDONAESCOLD` int(9) NULL COMMENT 'ESTABLECIMIENTO OLD',
    `ANIDONAANCOLD` int(9) NULL COMMENT 'ANIMAL OLD',
    `ANIDONAFECOLD` date NULL COMMENT 'FECHA OLD',
    `ANIDONAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN OLD',

    `ANIDONACODNEW` int(9) NULL COMMENT 'CÓDIGO NEW',
    `ANIDONATDCNEW` int(9) NULL COMMENT 'DONACION NEW',
    `ANIDONAESCNEW` int(9) NULL COMMENT 'ESTABLECIMIENTO NEW',
    `ANIDONAANCNEW` int(9) NULL COMMENT 'ANIMAL NEW',
    `ANIDONAFECNEW` date NULL COMMENT 'FECHA NEW',
    `ANIDONAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ANIMAL DONACION AUDITORÍA';

ALTER TABLE `ANIDON` ADD PRIMARY KEY (`ANIDONCOD`);
ALTER TABLE `ANIDON` MODIFY `ANIDONCOD` int(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `ANIDON` ADD KEY `ANIDONTDC` (`ANIDONTDC`);
ALTER TABLE `ANIDON` ADD CONSTRAINT `FK_ANIDONTDC` FOREIGN KEY (`ANIDONTDC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);

ALTER TABLE `ANIDON` ADD KEY `ANIDONESC` (`ANIDONESC`);
ALTER TABLE `ANIDON` ADD CONSTRAINT `FK_ANIDONESC` FOREIGN KEY (`ANIDONESC`) REFERENCES `mayordomo_default`.`ESTFIC` (`ESTFICCOD`);

ALTER TABLE `ANIDON` ADD KEY `ANIDONANC` (`ANIDONANC`);
ALTER TABLE `ANIDON` ADD CONSTRAINT `FK_ANIDONANC` FOREIGN KEY (`ANIDONANC`) REFERENCES `mayordomo_establecimiento`.`ANIFIC` (`ANIFICCOD`);

ALTER TABLE `ANIDONA` ADD PRIMARY KEY (`ANIDONACOD`);
ALTER TABLE `ANIDONA` MODIFY `ANIDONACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `ANIDONDLT`
  BEFORE DELETE ON `ANIDON`
  FOR EACH ROW
    INSERT INTO `ANIDONA` (`ANIDONAMET`, `ANIDONAEMP`, `ANIDONAUSU`, `ANIDONAFEC`, `ANIDONADIP`, `ANIDONACODOLD`, `ANIDONATDCOLD`, `ANIDONAESCOLD`, `ANIDONAANCOLD`, `ANIDONAFECOLD`, `ANIDONAOBSOLD`)
    VALUES ('DELETE', OLD.`ANIDONAEM`, OLD.`ANIDONAUS`, NOW(), OLD.`ANIDONAIP`, OLD.`ANIDONCOD`, OLD.`ANIDONTDC`, OLD.`ANIDONESC`, OLD.`ANIDONFEC`, OLD.`ANIDONANC`, OLD.`ANIDONOBS`);

CREATE TRIGGER `ANIDONINS`
  AFTER INSERT ON `ANIDON`
  FOR EACH ROW
    INSERT INTO `ANIDONA` (`ANIDONAMET`, `ANIDONAEMP`, `ANIDONAUSU`, `ANIDONAFEC`, `ANIDONADIP`, `ANIDONACODNEW`, `ANIDONATDCNEW`, `ANIDONAESCNEW`, `ANIDONAANCNEW`, `ANIDONAFECNEW`, `ANIDONAOBSNEW`)
    VALUES ('INSERT', NEW.`ANIDONAEM`, NEW.`ANIDONAUS`, NOW(), NEW.`ANIDONAIP`, NEW.`ANIDONCOD`, NEW.`ANIDONTDC`, NEW.`ANIDONESC`, NEW.`ANIDONFEC`, NEW.`ANIDONANC`, NEW.`ANIDONOBS`);

CREATE TRIGGER `ANIDONUPD`
  AFTER UPDATE ON `ANIDON`
  FOR EACH ROW
    INSERT INTO `ANIDONA` (`ANIDONAMET`, `ANIDONAEMP`, `ANIDONAUSU`, `ANIDONAFEC`, `ANIDONADIP`, `ANIDONACODOLD`, `ANIDONATDCOLD`, `ANIDONAESCOLD`, `ANIDONAANCOLD`, `ANIDONAFECOLD`, `ANIDONAOBSOLD`, `ANIDONACODNEW`, `ANIDONATDCNEW`, `ANIDONAESCNEW`, `ANIDONAANCNEW`, `ANIDONAFECNEW`, `ANIDONAOBSNEW`)
    VALUES ('UPDATE', NEW.`ANIDONAEM`, NEW.`ANIDONAUS`, NOW(), NEW.`ANIDONAIP`, OLD.`ANIDONCOD`, OLD.`ANIDONTDC`, OLD.`ANIDONESC`, OLD.`ANIDONFEC`, OLD.`ANIDONANC`, OLD.`ANIDONOBS`, NEW.`ANIDONCOD`, NEW.`ANIDONTDC`, NEW.`ANIDONESC`, NEW.`ANIDONFEC`, NEW.`ANIDONANC`, NEW.`ANIDONOBS`);