CREATE TABLE `ANIFIC` (
    `ANIFICCOD` int(9) NOT NULL COMMENT 'CÓDIGO',
    `ANIFICECC` int(9) NOT NULL COMMENT 'ESTADO',
    `ANIFICTOC` int(9) NOT NULL COMMENT 'ORIGEN',
    `ANIFICTRC` int(9) NOT NULL COMMENT 'RAZA',
    `ANIFICTCC` int(9) NOT NULL COMMENT 'CATEGORIA',
    `ANIFICTSC` int(9) NOT NULL COMMENT 'SUBCATEGORIA',
    `ANIFICESC` int(9) NOT NULL COMMENT 'ESTABLECIMIENTO',
    `ANIFICPEC` int(9) NOT NULL COMMENT 'PERSONA',
    `ANIFICCO1` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 1',
    `ANIFICCO2` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 2',
    `ANIFICCO3` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 3',
    `ANIFICCO4` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 4',
    `ANIFICCO5` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 5',
    `ANIFICCO6` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 6',
    `ANIFICOBS` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN',
    `ANIFICAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
    `ANIFICAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
    `ANIFICAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
    `ANIFICAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ANIMAL FICHA';

CREATE TABLE `ANIFICA` (
    `ANIFICACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `ANIFICAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `ANIFICAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
    `ANIFICAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `ANIFICAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `ANIFICADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `ANIFICACODOLD` int(9) NULL COMMENT 'CÓDIGO OLD',
    `ANIFICAECCOLD` int(9) NULL COMMENT 'ESTADO OLD',
    `ANIFICATOCOLD` int(9) NULL COMMENT 'ORIGEN OLD',
    `ANIFICATRCOLD` int(9) NULL COMMENT 'RAZA OLD',
    `ANIFICATCCOLD` int(9) NULL COMMENT 'CATEGORIA OLD',
    `ANIFICATSCOLD` int(9) NULL COMMENT 'SUBCATEGORIA OLD',
    `ANIFICAESCOLD` int(9) NULL COMMENT 'ESTABLECIMIENTO OLD',
    `ANIFICAPECOLD` int(9) NULL COMMENT 'PERSONA OLD',
    `ANIFICACO1OLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 1 OLD',
    `ANIFICACO2OLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 2 OLD',
    `ANIFICACO3OLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 3 OLD',
    `ANIFICACO4OLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 4 OLD',
    `ANIFICACO5OLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 5 OLD',
    `ANIFICACO6OLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 6 OLD',
    `ANIFICAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN OLD',

    `ANIFICACODNEW` int(9) NULL COMMENT 'CÓDIGO NEW',
    `ANIFICAECCNEW` int(9) NULL COMMENT 'ESTADO NEW',
    `ANIFICATOCNEW` int(9) NULL COMMENT 'ORIGEN NEW',
    `ANIFICATRCNEW` int(9) NULL COMMENT 'RAZA NEW',
    `ANIFICATCCNEW` int(9) NULL COMMENT 'CATEGORIA NEW',
    `ANIFICATSCNEW` int(9) NULL COMMENT 'SUBCATEGORIA NEW',
    `ANIFICAESCNEW` int(9) NULL COMMENT 'ESTABLECIMIENTO NEW',
    `ANIFICAPECNEW` int(9) NULL COMMENT 'PERSONA NEW',
    `ANIFICACO1NEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 1 NEW',
    `ANIFICACO2NEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 2 NEW',
    `ANIFICACO3NEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 3 NEW',
    `ANIFICACO4NEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 4 NEW',
    `ANIFICACO5NEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 5 NEW',
    `ANIFICACO6NEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO 6 NEW',
    `ANIFICAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ANIMAL FICHA AUDITORÍA';

ALTER TABLE `ANIFIC` ADD PRIMARY KEY (`ANIFICCOD`);
ALTER TABLE `ANIFIC` MODIFY `ANIFICCOD` int(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `ANIFIC` ADD KEY `ANIFICECC` (`ANIFICECC`);
ALTER TABLE `ANIFIC` ADD CONSTRAINT `FK_ANIFICECC` FOREIGN KEY (`ANIFICECC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);

ALTER TABLE `ANIFIC` ADD KEY `ANIFICTOC` (`ANIFICTOC`);
ALTER TABLE `ANIFIC` ADD CONSTRAINT `FK_ANIFICTOC` FOREIGN KEY (`ANIFICTOC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);

ALTER TABLE `ANIFIC` ADD KEY `ANIFICTRC` (`ANIFICTRC`);
ALTER TABLE `ANIFIC` ADD CONSTRAINT `FK_ANIFICTRC` FOREIGN KEY (`ANIFICTRC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);

ALTER TABLE `ANIFIC` ADD KEY `ANIFICTCC` (`ANIFICTCC`);
ALTER TABLE `ANIFIC` ADD CONSTRAINT `FK_ANIFICTCC` FOREIGN KEY (`ANIFICTCC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);

ALTER TABLE `ANIFIC` ADD KEY `ANIFICTSC` (`ANIFICTSC`);
ALTER TABLE `ANIFIC` ADD CONSTRAINT `FK_ANIFICTSC` FOREIGN KEY (`ANIFICTSC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);

ALTER TABLE `ANIFIC` ADD KEY `ANIFICESC` (`ANIFICESC`);
ALTER TABLE `ANIFIC` ADD CONSTRAINT `FK_AANIFICESC` FOREIGN KEY (`ANIFICESC`) REFERENCES `mayordomo_default`.`ESTFIC` (`ESTFICCOD`);

ALTER TABLE `ANIFIC` ADD KEY `ANIFICPEC` (`ANIFICPEC`);
ALTER TABLE `ANIFIC` ADD CONSTRAINT `FK_ANIFICPEC` FOREIGN KEY (`ANIFICPEC`) REFERENCES `mayordomo_establecimiento`.`ESTPER` (`ESTPERCOD`);

ALTER TABLE `ANIFICA` ADD PRIMARY KEY (`ANIFICACOD`);
ALTER TABLE `ANIFICA` MODIFY `ANIFICACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `ANIFICDLT` 
  BEFORE DELETE ON `ANIFIC` 
  FOR EACH ROW 
    INSERT INTO `ANIFICA` (`ANIFICAMET`, `ANIFICAEMP`, `ANIFICAUSU`, `ANIFICAFEC`, `ANIFICADIP`, `ANIFICACODOLD`, `ANIFICAECCOLD`, `ANIFICATOCOLD`, `ANIFICATRCOLD`, `ANIFICATCCOLD`, `ANIFICATSCOLD`, `ANIFICAESCOLD`, `ANIFICAPECOLD`, `ANIFICACO1OLD`, `ANIFICACO2OLD`, `ANIFICACO3OLD`, `ANIFICACO4OLD`, `ANIFICACO5OLD`, `ANIFICACO6OLD`, `ANIFICAOBSOLD`)
    VALUES ('DELETE', OLD.`ANIFICAEM`, OLD.`ANIFICAUS`, NOW(), OLD.`ANIFICAIP`, OLD.`ANIFICCOD`, OLD.`ANIFICECC`, OLD.`ANIFICTOC`, OLD.`ANIFICTRC`, OLD.`ANIFICTCC`, OLD.`ANIFICTSC`, OLD.`ANIFICESC`, OLD.`ANIFICPEC`, OLD.`ANIFICCO1`, OLD.`ANIFICCO2`, OLD.`ANIFICCO3`, OLD.`ANIFICCO4`, OLD.`ANIFICCO5`, OLD.`ANIFICCO6`, OLD.`ANIFICOBS`);

CREATE TRIGGER `ANIFICINS` 
  AFTER INSERT ON `ANIFIC` 
  FOR EACH ROW 
    INSERT INTO `ANIFICA` (`ANIFICAMET`, `ANIFICAEMP`, `ANIFICAUSU`, `ANIFICAFEC`, `ANIFICADIP`, `ANIFICACODNEW`, `ANIFICAECCNEW`, `ANIFICATOCNEW`, `ANIFICATRCNEW`, `ANIFICATCCNEW`, `ANIFICATSCNEW`, `ANIFICAESCNEW`, `ANIFICAPECNEW`, `ANIFICACO1NEW`, `ANIFICACO2NEW`, `ANIFICACO3NEW`, `ANIFICACO4NEW`, `ANIFICACO5NEW`, `ANIFICACO6NEW`, `ANIFICAOBSNEW`)
    VALUES ('INSERT', NEW.`ANIFICAEM`, NEW.`ANIFICAUS`, NOW(), NEW.`ANIFICAIP`, NEW.`ANIFICCOD`, NEW.`ANIFICECC`, NEW.`ANIFICTOC`, NEW.`ANIFICTRC`, NEW.`ANIFICTCC`, NEW.`ANIFICTSC`, NEW.`ANIFICESC`, NEW.`ANIFICPEC`, NEW.`ANIFICCO1`, NEW.`ANIFICCO2`, NEW.`ANIFICCO3`, NEW.`ANIFICCO4`, NEW.`ANIFICCO5`, NEW.`ANIFICCO6`, NEW.`ANIFICOBS`);

CREATE TRIGGER `ANIFICUPD` 
  AFTER UPDATE ON `ANIFIC` 
  FOR EACH ROW 
    INSERT INTO `ANIFICA` (`ANIFICAMET`, `ANIFICAEMP`, `ANIFICAUSU`, `ANIFICAFEC`, `ANIFICADIP`, `ANIFICACODOLD`, `ANIFICAECCOLD`, `ANIFICATOCOLD`, `ANIFICATRCOLD`, `ANIFICATCCOLD`, `ANIFICATSCOLD`, `ANIFICAESCOLD`, `ANIFICAPECOLD`, `ANIFICACO1OLD`, `ANIFICACO2OLD`, `ANIFICACO3OLD`, `ANIFICACO4OLD`, `ANIFICACO5OLD`, `ANIFICACO6OLD`, `ANIFICAOBSOLD`, `ANIFICACODNEW`, `ANIFICAECCNEW`, `ANIFICATOCNEW`, `ANIFICATRCNEW`, `ANIFICATCCNEW`, `ANIFICATSCNEW`, `ANIFICAESCNEW`, `ANIFICAPECNEW`, `ANIFICACO1NEW`, `ANIFICACO2NEW`, `ANIFICACO3NEW`, `ANIFICACO4NEW`, `ANIFICACO5NEW`, `ANIFICACO6NEW`, `ANIFICAOBSNEW`)
    VALUES ('UPDATE', NEW.`ANIFICAEM`, NEW.`ANIFICAUS`, NOW(), NEW.`ANIFICAIP`, OLD.`ANIFICCOD`, OLD.`ANIFICECC`, OLD.`ANIFICTOC`, OLD.`ANIFICTRC`, OLD.`ANIFICTCC`, OLD.`ANIFICTSC`, OLD.`ANIFICESC`, OLD.`ANIFICPEC`, OLD.`ANIFICCO1`, OLD.`ANIFICCO2`, OLD.`ANIFICCO3`, OLD.`ANIFICCO4`, OLD.`ANIFICCO5`, OLD.`ANIFICCO6`, OLD.`ANIFICOBS`, NEW.`ANIFICCOD`, NEW.`ANIFICECC`, NEW.`ANIFICTOC`, NEW.`ANIFICTRC`, NEW.`ANIFICTCC`, NEW.`ANIFICTSC`, NEW.`ANIFICESC`, NEW.`ANIFICPEC`, NEW.`ANIFICCO1`, NEW.`ANIFICCO2`, NEW.`ANIFICCO3`, NEW.`ANIFICCO4`, NEW.`ANIFICCO5`, NEW.`ANIFICCO6`, NEW.`ANIFICOBS`);