CREATE TABLE `ANIPES` (
  `ANIPESCOD` int(9) NOT NULL COMMENT 'CÓDIGO',
  `ANIPESTPC` int(9) NOT NULL COMMENT 'TIPO PESO',
  `ANIPESESC` int(9) NOT NULL COMMENT 'ESTABLECIMIENTO',
  `ANIPESANC` int(9) NOT NULL COMMENT 'ANIMAL',
  `ANIPESFEC` date NULL COMMENT 'FECHA',
  `ANIPESPES` decimal(10, 3) NULL COMMENT 'PESO',
  `ANIPESOBS` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN',
  `ANIPESAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
  `ANIPESAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
  `ANIPESAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
  `ANIPESAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ANIMAL PESO';

CREATE TABLE `ANIPESA` (
  `ANIPESACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
  `ANIPESAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
  `ANIPESAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
  `ANIPESAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
  `ANIPESAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
  `ANIPESADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

  `ANIPESACODOLD` int(9) NULL COMMENT 'CÓDIGO OLD',
  `ANIPESATPCOLD` int(9) NULL COMMENT 'TIPO PESO OLD',
  `ANIPESAESCOLD` int(9) NULL COMMENT 'ESTABLECIMIENTO OLD',
  `ANIPESAANCOLD` int(9) NULL COMMENT 'ANIMAL OLD',
  `ANIPESAFECOLD` date NULL COMMENT 'FECHA OLD',
  `ANIPESAPESOLD` decimal(10, 3) NULL COMMENT 'PESO OLD',
  `ANIPESAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN OLD',

  `ANIPESACODNEW` int(9) NULL COMMENT 'CÓDIGO NEW',
  `ANIPESATPCNEW` int(9) NULL COMMENT 'TIPO PESO NEW',
  `ANIPESAESCNEW` int(9) NULL COMMENT 'ESTABLECIMIENTO NEW',
  `ANIPESAANCNEW` int(9) NULL COMMENT 'ANIMAL NEW',
  `ANIPESAFECNEW` date NULL COMMENT 'FECHA NEW',
  `ANIPESAPESNEW` decimal(10, 3) NULL COMMENT 'PESO NEW',
  `ANIPESAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ANIMAL PESO AUDITORÍA';

ALTER TABLE `ANIPES` ADD PRIMARY KEY (`ANIPESCOD`);
ALTER TABLE `ANIPES` MODIFY `ANIPESCOD` int(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `ANIPES` ADD KEY `ANIPESTPC` (`ANIPESTPC`);
ALTER TABLE `ANIPES` ADD CONSTRAINT `FK_ANIPESTPC` FOREIGN KEY (`ANIPESTPC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);

ALTER TABLE `ANIPES` ADD KEY `ANIPESESC` (`ANIPESESC`);
ALTER TABLE `ANIPES` ADD CONSTRAINT `FK_ANIPESESC` FOREIGN KEY (`ANIPESESC`) REFERENCES `mayordomo_default`.`ESTFIC` (`ESTFICCOD`);

ALTER TABLE `ANIPES` ADD KEY `ANIPESANC` (`ANIPESANC`);
ALTER TABLE `ANIPES` ADD CONSTRAINT `FK_ANIPESANC` FOREIGN KEY (`ANIPESANC`) REFERENCES `mayordomo_establecimiento`.`ANIFIC` (`ANIFICCOD`);

ALTER TABLE `ANIPESA` ADD PRIMARY KEY (`ANIPESACOD`);
ALTER TABLE `ANIPESA` MODIFY `ANIPESACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `ANIPESDLT` 
  BEFORE DELETE ON `ANIPES` 
  FOR EACH ROW 
    INSERT INTO `ANIPESA` (`ANIPESAMET`, `ANIPESAEMP`, `ANIPESAUSU`, `ANIPESAFEC`, `ANIPESADIP`, `ANIPESACODOLD`, `ANIPESATPCOLD`, `ANIPESAESCOLD`, `ANIPESAANCOLD`, `ANIPESAFECOLD`, `ANIPESAPESOLD`, `ANIPESAOBSOLD`)
    VALUES ('DELETE', OLD.`ANIPESAEM`, OLD.`ANIPESAUS`, NOW(), OLD.`ANIPESAIP`, OLD.`ANIPESCOD`, OLD.`ANIPESTPC`, OLD.`ANIPESESC`, OLD.`ANIPESANC`, OLD.`ANIPESFEC`, OLD.`ANIPESPES`, OLD.`ANIPESOBS`);

CREATE TRIGGER `ANIPESINS` 
  AFTER INSERT ON `ANIPES` 
  FOR EACH ROW 
    INSERT INTO `ANIPESA` (`ANIPESAMET`, `ANIPESAEMP`, `ANIPESAUSU`, `ANIPESAFEC`, `ANIPESADIP`, `ANIPESACODNEW`, `ANIPESATPCNEW`, `ANIPESAESCNEW`, `ANIPESAANCNEW`, `ANIPESAFECNEW`, `ANIPESAPESNEW`, `ANIPESAOBSNEW`)
    VALUES ('INSERT', NEW.`ANIPESAEM`, NEW.`ANIPESAUS`, NOW(), NEW.`ANIPESAIP`, NEW.`ANIPESCOD`, NEW.`ANIPESTPC`, NEW.`ANIPESESC`, NEW.`ANIPESANC`, NEW.`ANIPESFEC`, NEW.`ANIPESPES`, NEW.`ANIPESOBS`);

CREATE TRIGGER `ANIPESUPD` 
  AFTER UPDATE ON `ANIPES` 
  FOR EACH ROW 
    INSERT INTO `ANIPESA` (`ANIPESAMET`, `ANIPESAEMP`, `ANIPESAUSU`, `ANIPESAFEC`, `ANIPESADIP`, `ANIPESACODOLD`, `ANIPESATPCOLD`, `ANIPESAESCOLD`, `ANIPESAANCOLD`, `ANIPESAFECOLD`, `ANIPESAPESOLD`, `ANIPESAOBSOLD`, `ANIPESACODNEW`, `ANIPESATPCNEW`, `ANIPESAESCNEW`, `ANIPESAANCNEW`, `ANIPESAFECNEW`, `ANIPESAPESNEW`, `ANIPESAOBSNEW`)
    VALUES ('UPDATE', NEW.`ANIPESAEM`, NEW.`ANIPESAUS`, NOW(), NEW.`ANIPESAIP`, OLD.`ANIPESCOD`, OLD.`ANIPESTPC`, OLD.`ANIPESESC`, OLD.`ANIPESANC`, OLD.`ANIPESFEC`, OLD.`ANIPESPES`, OLD.`ANIPESOBS`, NEW.`ANIPESCOD`, NEW.`ANIPESTPC`, NEW.`ANIPESESC`, NEW.`ANIPESANC`, NEW.`ANIPESFEC`, NEW.`ANIPESPES`, NEW.`ANIPESOBS`);