CREATE TABLE `DOMTRI` (
  `DOMTRICO1` int(9) NOT NULL COMMENT 'CÓDIGO DOMINIO 1',
  `DOMTRICO2` int(9) NOT NULL COMMENT 'CÓDIGO DOMINIO 2',
  `DOMTRICO3` int(9) NOT NULL COMMENT 'CÓDIGO DOMINIO 3',
  `DOMTRIEDC` int(9) NOT NULL COMMENT 'ESTADO',
  `DOMTRIVAL` char(50) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'DOMINIO',
  `DOMTRIOBS` varchar(5120) CHARACTER SET utf8 COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
  `DOMTRIAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
  `DOMTRIAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
  `DOMTRIAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
  `DOMTRIAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='DOMINIO';

CREATE TABLE `DOMTRIA` (
  `DOMTRIACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
  `DOMTRIAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
  `DOMTRIAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
  `DOMTRIAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
  `DOMTRIAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
  `DOMTRIADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',
  `DOMTRIACO1OLD` int(9) DEFAULT NULL COMMENT 'CÓDIGO DOMINIO 1 OLD',
  `DOMTRIACO2OLD` int(9) DEFAULT NULL COMMENT 'CÓDIGO DOMINIO 2 OLD',
  `DOMTRIACO3OLD` int(9) DEFAULT NULL COMMENT 'CÓDIGO DOMINIO 3 OLD',
  `DOMTRIAEDCOLD` int(9) DEFAULT NULL COMMENT 'ESTADO OLD',
  `DOMTRIAVALOLD` char(50) CHARACTER SET utf8 COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'DOMINIO OLD',
  `DOMTRIAOBSOLD` varchar(5120) CHARACTER SET utf8 COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN OLD',
  `DOMTRIACO1NEW` int(9) DEFAULT NULL COMMENT 'CÓDIGO DOMINIO 1 NEW',
  `DOMTRIACO2NEW` int(9) DEFAULT NULL COMMENT 'CÓDIGO DOMINIO 2 NEW',
  `DOMTRIACO3NEW` int(9) DEFAULT NULL COMMENT 'CÓDIGO DOMINIO 3 NEW',
  `DOMTRIAEDCNEW` int(9) DEFAULT NULL COMMENT 'ESTADO NEW',
  `DOMTRIAVALNEW` char(50) CHARACTER SET utf8 COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'DOMINIO NEW',
  `DOMTRIAOBSNEW` varchar(5120) CHARACTER SET utf8 COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='DOMINIO AUDITORÍA';

ALTER TABLE `DOMTRI` ADD PRIMARY KEY `DOMTRICOD` (`DOMTRICO1`, `DOMTRICO2`, `DOMTRICO3`);
ALTER TABLE `DOMTRI` ADD KEY `DOMTRIEDC` (`DOMTRIEDC`);
ALTER TABLE `DOMTRI` ADD CONSTRAINT `FK_DOMTRICO1` FOREIGN KEY (`DOMTRICO1`) REFERENCES `DOMFIC` (`DOMFICCOD`);
ALTER TABLE `DOMTRI` ADD CONSTRAINT `FK_DOMTRICO2` FOREIGN KEY (`DOMTRICO2`) REFERENCES `DOMFIC` (`DOMFICCOD`);
ALTER TABLE `DOMTRI` ADD CONSTRAINT `FK_DOMTRICO3` FOREIGN KEY (`DOMTRICO3`) REFERENCES `DOMFIC` (`DOMFICCOD`);
ALTER TABLE `DOMTRI` ADD CONSTRAINT `FK_DOMTRIEDC` FOREIGN KEY (`DOMTRIEDC`) REFERENCES `DOMFIC` (`DOMFICCOD`);

ALTER TABLE `DOMTRIA` ADD PRIMARY KEY (`DOMTRIACOD`);
ALTER TABLE `DOMTRIA` MODIFY `DOMTRIACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `DOMTRIDLT` 
  BEFORE DELETE ON `DOMTRI` 
  FOR EACH ROW 
    INSERT INTO `DOMTRIA` (`DOMTRIAMET`, `DOMTRIAEMP`, `DOMTRIAUSU`, `DOMTRIAFEC`, `DOMTRIADIP`, `DOMTRIACO1OLD`, `DOMTRIACO2OLD`, `DOMTRIACO3OLD`, `DOMTRIAEDCOLD`, `DOMTRIAVALOLD`, `DOMTRIAOBSOLD`)
                  VALUES ('DELETE', OLD.`DOMTRIAEM`, OLD.`DOMTRIAUS`, NOW(), OLD.`DOMTRIAIP`, OLD.`DOMTRICO1`, OLD.`DOMTRICO2`, OLD.`DOMTRICO3`, OLD.`DOMTRIEDC`, OLD.`DOMTRIVAL`, OLD.`DOMTRIOBS`);

CREATE TRIGGER `DOMTRIINS` 
  AFTER INSERT ON `DOMTRI` 
  FOR EACH ROW 
    INSERT INTO `DOMTRIA` (`DOMTRIAMET`, `DOMTRIAEMP`, `DOMTRIAUSU`, `DOMTRIAFEC`, `DOMTRIADIP`, `DOMTRIACO1NEW`, `DOMTRIACO2NEW`, `DOMTRIACO3NEW`, `DOMTRIAEDCNEW`, `DOMTRIAVALNEW`, `DOMTRIAOBSNEW`)
                  VALUES ('INSERT', NEW.`DOMTRIAEM`, NEW.`DOMTRIAUS`, NOW(), NEW.`DOMTRIAIP`, NEW.`DOMTRICO1`, NEW.`DOMTRICO2`, NEW.`DOMTRICO3`, NEW.`DOMTRIEDC`, NEW.`DOMTRIVAL`, NEW.`DOMTRIOBS`);

CREATE TRIGGER `DOMTRIUPD` 
  AFTER UPDATE ON `DOMTRI` 
  FOR EACH ROW 
    INSERT INTO `DOMTRIA` (`DOMTRIAMET`, `DOMTRIAEMP`, `DOMTRIAUSU`, `DOMTRIAFEC`, `DOMTRIADIP`, `DOMTRIACO1OLD`, `DOMTRIACO2OLD`, `DOMTRIACO3OLD`, `DOMTRIAEDCOLD`, `DOMTRIAVALOLD`, `DOMTRIAOBSOLD`, `DOMTRIACO1NEW`, `DOMTRIACO2NEW`, `DOMTRIACO3NEW`, `DOMTRIAEDCNEW`, `DOMTRIAVALNEW`, `DOMTRIAOBSNEW`)
                  VALUES ('UPDATE', NEW.`DOMTRIAEM`, NEW.`DOMTRIAUS`, NOW(), NEW.`DOMTRIAIP`, OLD.`DOMTRICO1`, OLD.`DOMTRICO2`, OLD.`DOMTRICO3`, OLD.`DOMTRIEDC`, OLD.`DOMTRIVAL`, OLD.`DOMTRIOBS`, NEW.`DOMTRICO1`, NEW.`DOMTRICO2`, NEW.`DOMTRICO3`, NEW.`DOMTRIEDC`, NEW.`DOMTRIVAL`, NEW.`DOMTRIOBS`);