CREATE TABLE `ESTCAT` (
    `ESTCATESC` int(9) NOT NULL COMMENT 'CÓDIGO ESTABLECIMIENTO',
    `ESTCATTCC` int(9) NOT NULL COMMENT 'CÓDIGO TIPO CATEGORÍA',
    `ESTCATECC` int(9) NOT NULL COMMENT 'ESTADO',
    `ESTCATCAN` int(9) NULL COMMENT 'CANTIDAD',
    `ESTCATPES` float(5,4) NULL COMMENT 'PESO',
    `ESTCATOBS` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN',
    `ESTCATAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
    `ESTCATAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
    `ESTCATAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
    `ESTCATAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ESTABLECIMIENTO CATEGORÍA';

CREATE TABLE `ESTCATA` (
    `ESTCATACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `ESTCATAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `ESTCATAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
    `ESTCATAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `ESTCATAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `ESTCATADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',
    `ESTCATAESCOLD` int(9) NULL COMMENT 'CÓDIGO ESTABLECIMIENTO OLD',
    `ESTCATATCCOLD` int(9) NULL COMMENT 'CÓDIGO TIPO CATEGORÍA OLD',
    `ESTCATAECCOLD` int(9) NULL COMMENT 'ESTADO OLD',
    `ESTCATACANOLD` int(9) NULL COMMENT 'CANTIDAD OLD',
    `ESTCATAPESOLD` float(5,4) NULL COMMENT 'PESO OLD',
    `ESTCATAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN OLD',
    `ESTCATAESCNEW` int(9) NULL COMMENT 'CÓDIGO ESTABLECIMIENTO NEW',
    `ESTCATATCCNEW` int(9) NULL COMMENT 'CÓDIGO TIPO CATEGORÍA NEW',
    `ESTCATAECCNEW` int(9) NULL COMMENT 'ESTADO NEW',
    `ESTCATACANNEW` int(9) NULL COMMENT 'CANTIDAD NEW',
    `ESTCATAPESNEW` float(5,4) NULL COMMENT 'PESO NEW',
    `ESTCATAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ESTABLECIMIENTO CATEGORÍA AUDITORÍA';

ALTER TABLE `ESTCAT` ADD KEY `ESTCATESC` (`ESTCATESC`);
ALTER TABLE `ESTCAT` ADD KEY `ESTCATTCC` (`ESTCATTCC`);
ALTER TABLE `ESTCAT` ADD KEY `ESTCATECC` (`ESTCATECC`);
ALTER TABLE `ESTCAT` ADD PRIMARY KEY `ESTCATCOD` (`ESTCATESC`, `ESTCATTCC`);
ALTER TABLE `ESTCAT` ADD CONSTRAINT `FK_ESTCAT1` FOREIGN KEY (`ESTCATESC`) REFERENCES `mayordomo_default`.`ESTFIC` (`ESTFICCOD`);
ALTER TABLE `ESTCAT` ADD CONSTRAINT `FK_ESTCAT2` FOREIGN KEY (`ESTCATTCC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);
ALTER TABLE `ESTCAT` ADD CONSTRAINT `FK_ESTCAT3` FOREIGN KEY (`ESTCATECC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);

ALTER TABLE `ESTCATA` ADD PRIMARY KEY (`ESTCATACOD`);
ALTER TABLE `ESTCATA` MODIFY `ESTCATACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `ESTCATDLT` 
  BEFORE DELETE ON `ESTCAT` 
  FOR EACH ROW 
    INSERT INTO `ESTCATA` (`ESTCATAMET`, `ESTCATAEMP`, `ESTCATAUSU`, `ESTCATAFEC`, `ESTCATADIP`, `ESTCATAESCOLD`, `ESTCATATCCOLD`, `ESTCATAECCOLD`, `ESTCATACANOLD`, `ESTCATAPESOLD`, `ESTCATAOBSOLD`)
                  VALUES ('DELETE', OLD.`ESTCATAEM`, OLD.`ESTCATAUS`, NOW(), OLD.`ESTCATAIP`, OLD.`ESTCATESC`,  OLD.`ESTCATTCC`,  OLD.`ESTCATECC`,  OLD.`ESTCATCAN`,  OLD.`ESTCATPES`,  OLD.`ESTCATOBS`);

CREATE TRIGGER `ESTCATINS` 
  AFTER INSERT ON `ESTCAT` 
  FOR EACH ROW 
    INSERT INTO `ESTCATA` (`ESTCATAMET`, `ESTCATAEMP`, `ESTCATAUSU`, `ESTCATAFEC`, `ESTCATADIP`, `ESTCATAESCNEW`, `ESTCATATCCNEW`, `ESTCATAECCNEW`, `ESTCATACANNEW`, `ESTCATAPESNEW`, `ESTCATAOBSNEW`)
                  VALUES ('INSERT', NEW.`ESTCATAEM`, NEW.`ESTCATAUS`, NOW(), NEW.`ESTCATAIP`, NEW.`ESTCATESC`, NEW.`ESTCATTCC`, NEW.`ESTCATECC`, NEW.`ESTCATCAN`, NEW.`ESTCATPES`, NEW.`ESTCATOBS`);

CREATE TRIGGER `ESTCATUPD` 
  AFTER UPDATE ON `ESTCAT` 
  FOR EACH ROW 
    INSERT INTO `ESTCATA` (`ESTCATAMET`, `ESTCATAEMP`, `ESTCATAUSU`, `ESTCATAFEC`, `ESTCATADIP`, `ESTCATAESCOLD`, `ESTCATATCCOLD`, `ESTCATAECCOLD`, `ESTCATACANOLD`, `ESTCATAPESOLD`, `ESTCATAOBSOLD`,  `ESTCATAESCNEW`, `ESTCATATCCNEW`, `ESTCATAECCNEW`, `ESTCATACANNEW`, `ESTCATAPESNEW`, `ESTCATAOBSNEW`)
                  VALUES ('UPDATE', NEW.`ESTCATAEM`, NEW.`ESTCATAUS`, NOW(), NEW.`ESTCATAIP`, OLD.`ESTCATESC`,  OLD.`ESTCATTCC`,  OLD.`ESTCATECC`,  OLD.`ESTCATCAN`,  OLD.`ESTCATPES`,  OLD.`ESTCATOBS`, NEW.`ESTCATESC`, NEW.`ESTCATTCC`, NEW.`ESTCATECC`, NEW.`ESTCATCAN`, NEW.`ESTCATPES`, NEW.`ESTCATOBS`);