CREATE TABLE `ESTFIC` (
    `ESTFICCOD` int(9) NOT NULL COMMENT 'CÓDIGO',
    `ESTFICECC` int(9) NOT NULL COMMENT 'ESTADO',
    `ESTFICTEC` int(9) NOT NULL COMMENT 'TIPO ESTABLECIMIENTO',
    `ESTFICTFC` int(9) NOT NULL COMMENT 'TIPO FINALIDAD',
    `ESTFICPEC` int(9) NOT NULL COMMENT 'PERSONA',
    `ESTFICDIC` int(6) NOT NULL COMMENT 'DISTRITO',
    `ESTFICNOM` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'NOMBRE',
    `ESTFICTHE` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'TOTAL HECTAREA',
    `ESTFICTPO` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'TOTAL POTRERO',
    `ESTFICCO1` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CODIGO 1',
    `ESTFICCO2` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CODIGO 2',
    `ESTFICCO3` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CODIGO 3',
    `ESTFICLAT` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'LATITUD',
    `ESTFICLON` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'LONGITUD',
    `ESTFICOBS` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN',
    `ESTFICAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
    `ESTFICAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
    `ESTFICAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
    `ESTFICAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ESTABLECIMIENTO';

CREATE TABLE `ESTFICA` (
    `ESTFICACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `ESTFICAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `ESTFICAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
    `ESTFICAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `ESTFICAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `ESTFICADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',
    `ESTFICACODOLD` int(9) NULL COMMENT 'CÓDIGO OLD',
    `ESTFICAECCOLD` int(9) NULL COMMENT 'ESTADO OLD',
    `ESTFICATECOLD` int(9) NULL COMMENT 'TIPO ESTABLECIMIENTO OLD',
    `ESTFICATFCOLD` int(9) NULL COMMENT 'TIPO FINALIDAD OLD',
    `ESTFICAPECOLD` int(9) NULL COMMENT 'PERSONA OLD',
    `ESTFICADICOLD` int(6) NULL COMMENT 'DISTRITO OLD',
    `ESTFICANOMOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE OLD',
    `ESTFICATHEOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'TOTAL HECTAREA OLD',
    `ESTFICATPOOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'TOTAL POTRERO OLD',
    `ESTFICACO1OLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CODIGO 1 OLD',
    `ESTFICACO2OLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CODIGO 2 OLD',
    `ESTFICACO3OLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CODIGO 3 OLD',
    `ESTFICALATOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'LATITUD OLD',
    `ESTFICALONOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'LONGITUD OLD',
    `ESTFICAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN OLD',
    `ESTFICACODNEW` int(9) NULL COMMENT 'CÓDIGO NEW',
    `ESTFICAECCNEW` int(9) NULL COMMENT 'ESTADO NEW',
    `ESTFICATECNEW` int(9) NULL COMMENT 'TIPO ESTABLECIMIENTO NEW',
    `ESTFICATFCNEW` int(9) NULL COMMENT 'TIPO FINALIDAD NEW',
    `ESTFICAPECNEW` int(9) NULL COMMENT 'PERSONA NEW',
    `ESTFICADICNEW` int(6) NULL COMMENT 'DISTRITO NEW',
    `ESTFICANOMNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE NEW',
    `ESTFICATHENEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'TOTAL HECTAREA NEW',
    `ESTFICATPONEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'TOTAL POTRERO NEW',
    `ESTFICACO1NEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CODIGO 1 NEW',
    `ESTFICACO2NEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CODIGO 2 NEW',
    `ESTFICACO3NEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CODIGO 3 NEW',
    `ESTFICALATNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'LATITUD NEW',
    `ESTFICALONNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'LONGITUD NEW',
    `ESTFICAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ESTABLECIMIENTO AUDITORÍA';

ALTER TABLE `ESTFIC` ADD PRIMARY KEY (`ESTFICCOD`);
ALTER TABLE `ESTFIC` ADD KEY `ESTFICECC` (`ESTFICECC`);
ALTER TABLE `ESTFIC` ADD KEY `ESTFICTEC` (`ESTFICTEC`);
ALTER TABLE `ESTFIC` ADD KEY `ESTFICTFC` (`ESTFICTFC`);
ALTER TABLE `ESTFIC` ADD KEY `ESTFICPEC` (`ESTFICPEC`);
ALTER TABLE `ESTFIC` ADD KEY `ESTFICDIC` (`ESTFICDIC`);
ALTER TABLE `ESTFIC` MODIFY `ESTFICCOD` int(6) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;
ALTER TABLE `ESTFIC` ADD CONSTRAINT `FK_ESTFICECC` FOREIGN KEY (`ESTFICECC`) REFERENCES `DOMFIC` (`DOMFICCOD`);
ALTER TABLE `ESTFIC` ADD CONSTRAINT `FK_ESTFICTEC` FOREIGN KEY (`ESTFICTEC`) REFERENCES `DOMFIC` (`DOMFICCOD`);
ALTER TABLE `ESTFIC` ADD CONSTRAINT `FK_ESTFICTFC` FOREIGN KEY (`ESTFICTFC`) REFERENCES `DOMFIC` (`DOMFICCOD`);
ALTER TABLE `ESTFIC` ADD CONSTRAINT `FK_ESTFICPEC` FOREIGN KEY (`ESTFICPEC`) REFERENCES `PERFIC` (`PERFICCOD`);
ALTER TABLE `ESTFIC` ADD CONSTRAINT `FK_ESTFICDIC` FOREIGN KEY (`ESTFICDIC`) REFERENCES `LOCDIS` (`LOCDISCOD`);

ALTER TABLE `ESTFICA` ADD PRIMARY KEY (`ESTFICACOD`);
ALTER TABLE `ESTFICA` MODIFY `ESTFICACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `ESTFICDLT` 
  BEFORE DELETE ON `ESTFIC` 
  FOR EACH ROW 
    INSERT INTO `ESTFICA` (`ESTFICAMET`, `ESTFICAEMP`, `ESTFICAUSU`, `ESTFICAFEC`, `ESTFICADIP`, `ESTFICACODOLD`, `ESTFICAECCOLD`, `ESTFICATECOLD`, `ESTFICATFCOLD`, `ESTFICAPECOLD`, `ESTFICADICOLD`, `ESTFICANOMOLD`, `ESTFICATHEOLD`, `ESTFICATPOOLD`, `ESTFICACO1OLD`, `ESTFICACO2OLD`, `ESTFICACO3OLD`, `ESTFICALATOLD`, `ESTFICALONOLD`, `ESTFICAOBSOLD`)
                  VALUES ('DELETE', OLD.`ESTFICAEM`, OLD.`ESTFICAUS`, NOW(), OLD.`ESTFICAIP`, OLD.`ESTFICCOD`, OLD.`ESTFICECC`, OLD.`ESTFICTEC`, OLD.`ESTFICTFC`, OLD.`ESTFICPEC`, OLD.`ESTFICDIC`, OLD.`ESTFICNOM`, OLD.`ESTFICTHE`, OLD.`ESTFICTPO`, OLD.`ESTFICCO1`, OLD.`ESTFICCO2`, OLD.`ESTFICCO3`, OLD.`ESTFICLAT`, OLD.`ESTFICLON`, OLD.`ESTFICOBS`);

CREATE TRIGGER `ESTFICINS` 
  AFTER INSERT ON `ESTFIC` 
  FOR EACH ROW 
    INSERT INTO `ESTFICA` (`ESTFICAMET`, `ESTFICAEMP`, `ESTFICAUSU`, `ESTFICAFEC`, `ESTFICADIP`, `ESTFICACODNEW`, `ESTFICAECCNEW`, `ESTFICATECNEW`, `ESTFICATFCNEW`, `ESTFICAPECNEW`, `ESTFICADICNEW`, `ESTFICANOMNEW`, `ESTFICATHENEW`, `ESTFICATPONEW`, `ESTFICACO1NEW`, `ESTFICACO2NEW`, `ESTFICACO3NEW`, `ESTFICALATNEW`, `ESTFICALONNEW`, `ESTFICAOBSNEW`)
                  VALUES ('INSERT', NEW.`ESTFICAEM`, NEW.`ESTFICAUS`, NOW(), NEW.`ESTFICAIP`, NEW.`ESTFICCOD`, NEW.`ESTFICECC`, NEW.`ESTFICTEC`, NEW.`ESTFICTFC`, NEW.`ESTFICPEC`, NEW.`ESTFICDIC`, NEW.`ESTFICNOM`, NEW.`ESTFICTHE`, NEW.`ESTFICTPO`, NEW.`ESTFICCO1`, NEW.`ESTFICCO2`, NEW.`ESTFICCO3`, NEW.`ESTFICLAT`, NEW.`ESTFICLON`, NEW.`ESTFICOBS`);

CREATE TRIGGER `ESTFICUPD` 
  AFTER UPDATE ON `ESTFIC` 
  FOR EACH ROW 
    INSERT INTO `ESTFICA` (`ESTFICAMET`, `ESTFICAEMP`, `ESTFICAUSU`, `ESTFICAFEC`, `ESTFICADIP`, `ESTFICACODOLD`, `ESTFICAECCOLD`, `ESTFICATECOLD`, `ESTFICATFCOLD`, `ESTFICAPECOLD`, `ESTFICADICOLD`, `ESTFICANOMOLD`, `ESTFICATHEOLD`, `ESTFICATPOOLD`, `ESTFICACO1OLD`, `ESTFICACO2OLD`, `ESTFICACO3OLD`, `ESTFICALATOLD`, `ESTFICALONOLD`, `ESTFICAOBSOLD`, `ESTFICACODNEW`, `ESTFICAECCNEW`, `ESTFICATECNEW`, `ESTFICATFCNEW`, `ESTFICAPECNEW`, `ESTFICADICNEW`, `ESTFICANOMNEW`, `ESTFICATHENEW`, `ESTFICATPONEW`, `ESTFICACO1NEW`, `ESTFICACO2NEW`, `ESTFICACO3NEW`, `ESTFICALATNEW`, `ESTFICALONNEW`, `ESTFICAOBSNEW`)
                  VALUES ('UPDATE', NEW.`ESTFICAEM`, NEW.`ESTFICAUS`, NOW(), NEW.`ESTFICAIP`, OLD.`ESTFICCOD`, OLD.`ESTFICECC`, OLD.`ESTFICTEC`, OLD.`ESTFICTFC`, OLD.`ESTFICPEC`, OLD.`ESTFICDIC`, OLD.`ESTFICNOM`, OLD.`ESTFICTHE`, OLD.`ESTFICTPO`, OLD.`ESTFICCO1`, OLD.`ESTFICCO2`, OLD.`ESTFICCO3`, OLD.`ESTFICLAT`, OLD.`ESTFICLON`, OLD.`ESTFICOBS`, NEW.`ESTFICCOD`, NEW.`ESTFICECC`, NEW.`ESTFICTEC`, NEW.`ESTFICTFC`, NEW.`ESTFICPEC`, NEW.`ESTFICDIC`, NEW.`ESTFICNOM`, NEW.`ESTFICTHE`, NEW.`ESTFICTPO`, NEW.`ESTFICCO1`, NEW.`ESTFICCO2`, NEW.`ESTFICCO3`, NEW.`ESTFICLAT`, NEW.`ESTFICLON`, NEW.`ESTFICOBS`);
