CREATE TABLE `ESTLOT` (
    `ESTLOTCOD` int(9) NOT NULL COMMENT 'CÓDIGO',
    `ESTLOTECC` int(9) NOT NULL COMMENT 'ESTADO',
    `ESTLOTESC` int(9) NOT NULL COMMENT 'ESTABLECIMIENTO',
    `ESTLOTNOM` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'NOMBRE',
    `ESTLOTOBS` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN',
    `ESTLOTAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
    `ESTLOTAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
    `ESTLOTAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
    `ESTLOTAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ESTABLECIMIENTO SECCION';

CREATE TABLE `ESTLOTA` (
    `ESTLOTACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `ESTLOTAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `ESTLOTAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
    `ESTLOTAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `ESTLOTAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `ESTLOTADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `ESTLOTACODOLD` int(9) NULL COMMENT 'CÓDIGO OLD',
    `ESTLOTAECCOLD` int(9) NULL COMMENT 'ESTADO OLD',
    `ESTLOTAESCOLD` int(9) NULL COMMENT 'ESTABLECIMIENTO OLD',
    `ESTLOTANOMOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE OLD',
    `ESTLOTAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN OLD',

    `ESTLOTACODNEW` int(9) NULL COMMENT 'CÓDIGO NEW',
    `ESTLOTAECCNEW` int(9) NULL COMMENT 'ESTADO NEW',
    `ESTLOTAESCNEW` int(9) NULL COMMENT 'ESTABLECIMIENTO NEW',
    `ESTLOTANOMNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE NEW',
    `ESTLOTAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ESTABLECIMIENTO SECCION AUDITORÍA';

ALTER TABLE `ESTLOT` ADD PRIMARY KEY (`ESTLOTCOD`);
ALTER TABLE `ESTLOT` MODIFY `ESTLOTCOD` int(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `ESTLOT` ADD KEY `ESTLOTECC` (`ESTLOTECC`);
ALTER TABLE `ESTLOT` ADD KEY `ESTLOTESC` (`ESTLOTESC`);

ALTER TABLE `ESTLOT` ADD CONSTRAINT `FK_ESTLOTECC` FOREIGN KEY (`ESTLOTECC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);
ALTER TABLE `ESTLOT` ADD CONSTRAINT `FK_ESTLOTESC` FOREIGN KEY (`ESTLOTESC`) REFERENCES `mayordomo_default`.`ESTFIC` (`ESTFICCOD`);

ALTER TABLE `ESTLOTA` ADD PRIMARY KEY (`ESTLOTACOD`);
ALTER TABLE `ESTLOTA` MODIFY `ESTLOTACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `ESTLOTDLT` 
  BEFORE DELETE ON `ESTLOT` 
  FOR EACH ROW 
    INSERT INTO `ESTLOTA` (`ESTLOTAMET`, `ESTLOTAEMP`, `ESTLOTAUSU`, `ESTLOTAFEC`, `ESTLOTADIP`, `ESTLOTACODOLD`, `ESTLOTAECCOLD`, `ESTLOTAESCOLD`, `ESTLOTANOMOLD`, `ESTLOTAOBSOLD`)
    VALUES ('DELETE', OLD.`ESTLOTAEM`, OLD.`ESTLOTAUS`, NOW(), OLD.`ESTLOTAIP`, OLD.`ESTLOTCOD`, OLD.`ESTLOTECC`, OLD.`ESTLOTESC`, OLD.`ESTLOTNOM`, OLD.`ESTLOTOBS`);

CREATE TRIGGER `ESTLOTINS` 
  AFTER INSERT ON `ESTLOT` 
  FOR EACH ROW 
    INSERT INTO `ESTLOTA` (`ESTLOTAMET`, `ESTLOTAEMP`, `ESTLOTAUSU`, `ESTLOTAFEC`, `ESTLOTADIP`, `ESTLOTACODNEW`, `ESTLOTAECCNEW`, `ESTLOTAESCNEW`, `ESTLOTANOMNEW`, `ESTLOTAOBSNEW`)
    VALUES ('INSERT', NEW.`ESTLOTAEM`, NEW.`ESTLOTAUS`, NOW(), NEW.`ESTLOTAIP`, NEW.`ESTLOTCOD`, NEW.`ESTLOTECC`, NEW.`ESTLOTESC`, NEW.`ESTLOTNOM`, NEW.`ESTLOTOBS`);

CREATE TRIGGER `ESTLOTUPD` 
  AFTER UPDATE ON `ESTLOT` 
  FOR EACH ROW 
    INSERT INTO `ESTLOTA` (`ESTLOTAMET`, `ESTLOTAEMP`, `ESTLOTAUSU`, `ESTLOTAFEC`, `ESTLOTADIP`, `ESTLOTACODOLD`, `ESTLOTAECCOLD`, `ESTLOTAESCOLD`, `ESTLOTANOMOLD`, `ESTLOTAOBSOLD`, `ESTLOTACODNEW`, `ESTLOTAECCNEW`, `ESTLOTAESCNEW`, `ESTLOTANOMNEW`, `ESTLOTAOBSNEW`)
    VALUES ('UPDATE', NEW.`ESTLOTAEM`, NEW.`ESTLOTAUS`, NOW(), NEW.`ESTLOTAIP`, OLD.`ESTLOTCOD`, OLD.`ESTLOTECC`, OLD.`ESTLOTESC`, OLD.`ESTLOTNOM`, OLD.`ESTLOTOBS`, NEW.`ESTLOTCOD`, NEW.`ESTLOTECC`, NEW.`ESTLOTESC`, NEW.`ESTLOTNOM`, NEW.`ESTLOTOBS`);
