CREATE TABLE `ESTPOB` (
    `ESTPOBCOD` int(9) NOT NULL COMMENT 'CÓDIGO',
    `ESTPOBTOC` int(9) NOT NULL COMMENT 'ORIGEN',
    `ESTPOBTRC` int(9) NOT NULL COMMENT 'RAZA',
    `ESTPOBTSC` int(9) NOT NULL COMMENT 'SUBCATEGORIA',
    `ESTPOBESC` int(9) NOT NULL COMMENT 'ESTABLECIMIENTO',
    `ESTPOBPEC` int(9) NOT NULL COMMENT 'PERSONA',
    `ESTPOBCAN` int(10) NULL COMMENT 'CANTIDAD',
    `ESTPOBPES` decimal(10, 2) NULL COMMENT 'PESO PROMEDIO',
    `ESTPOBOBS` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN',
    `ESTPOBAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
    `ESTPOBAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
    `ESTPOBAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
    `ESTPOBAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ESTABLECIMIENTO POBLACIÓN';

CREATE TABLE `ESTPOBA` (
    `ESTPOBACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `ESTPOBAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `ESTPOBAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
    `ESTPOBAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `ESTPOBAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `ESTPOBADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `ESTPOBACODOLD` int(9) NULL COMMENT 'CÓDIGO OLD',
    `ESTPOBATOCOLD` int(9) NULL COMMENT 'ORIGEN OLD',
    `ESTPOBATRCOLD` int(9) NULL COMMENT 'RAZA OLD',
    `ESTPOBATSCOLD` int(9) NULL COMMENT 'SUBCATEGORIA OLD',
    `ESTPOBAESCOLD` int(9) NULL COMMENT 'ESTABLECIMIENTO OLD',
    `ESTPOBAPECOLD` int(9) NULL COMMENT 'PERSONA OLD',
    `ESTPOBACANOLD` int(10) NULL COMMENT 'CANTIDAD OLD',
    `ESTPOBAPESOLD` decimal(10, 2) NULL COMMENT 'PESO PROMEDIO OLD',
    `ESTPOBAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN OLD',

    `ESTPOBACODNEW` int(9) NULL COMMENT 'CÓDIGO NEW',
    `ESTPOBATOCNEW` int(9) NULL COMMENT 'ORIGEN NEW',
    `ESTPOBATRCNEW` int(9) NULL COMMENT 'RAZA NEW',
    `ESTPOBATSCNEW` int(9) NULL COMMENT 'SUBCATEGORIA NEW',
    `ESTPOBAESCNEW` int(9) NULL COMMENT 'ESTABLECIMIENTO NEW',
    `ESTPOBAPECNEW` int(9) NULL COMMENT 'PERSONA NEW',
    `ESTPOBACANNEW` int(10) NULL COMMENT 'CANTIDAD NEW',
    `ESTPOBAPESNEW` decimal(10, 2) NULL COMMENT 'PESO PROMEDIO NEW',
    `ESTPOBAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN NEW'

) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ESTABLECIMIENTO POBLACIÓN AUDITORÍA';

ALTER TABLE `ESTPOB` ADD PRIMARY KEY (`ESTPOBCOD`);
ALTER TABLE `ESTPOB` MODIFY `ESTPOBCOD` int(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `ESTPOB` ADD KEY `ESTPOBTOC` (`ESTPOBTOC`);
ALTER TABLE `ESTPOB` ADD CONSTRAINT `FK_ESTPOBTOC` FOREIGN KEY (`ESTPOBTOC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);

ALTER TABLE `ESTPOB` ADD KEY `ESTPOBTRC` (`ESTPOBTRC`);
ALTER TABLE `ESTPOB` ADD CONSTRAINT `FK_ESTPOBTRC` FOREIGN KEY (`ESTPOBTRC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);

ALTER TABLE `ESTPOB` ADD KEY `ESTPOBTSC` (`ESTPOBTSC`);
ALTER TABLE `ESTPOB` ADD CONSTRAINT `FK_ESTPOBTSC` FOREIGN KEY (`ESTPOBTSC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);

ALTER TABLE `ESTPOB` ADD KEY `ESTPOBESC` (`ESTPOBESC`);
ALTER TABLE `ESTPOB` ADD CONSTRAINT `FK_ESTPOBESC` FOREIGN KEY (`ESTPOBESC`) REFERENCES `mayordomo_default`.`ESTFIC` (`ESTFICCOD`);

ALTER TABLE `ESTPOB` ADD KEY `ESTPOBPEC` (`ESTPOBPEC`);
ALTER TABLE `ESTPOB` ADD CONSTRAINT `FK_ESTPOBPEC` FOREIGN KEY (`ESTPOBPEC`) REFERENCES `mayordomo_establecimiento`.`ESTPER` (`ESTPERCOD`);

ALTER TABLE `ESTPOBA` ADD PRIMARY KEY (`ESTPOBACOD`);
ALTER TABLE `ESTPOBA` MODIFY `ESTPOBACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `ESTPOBDLT` 
  BEFORE DELETE ON `ESTPOB` 
  FOR EACH ROW 
    INSERT INTO `ESTPOBA` (`ESTPOBAMET`, `ESTPOBAEMP`, `ESTPOBAUSU`, `ESTPOBAFEC`, `ESTPOBADIP`, `ESTPOBACODOLD`, `ESTPOBATOCOLD`, `ESTPOBATRCOLD`, `ESTPOBATSCOLD`, `ESTPOBAESCOLD`, `ESTPOBAPECOLD`, `ESTPOBACANOLD`, `ESTPOBAPESOLD`, `ESTPOBAOBSOLD`)
    VALUES ('DELETE', OLD.`ESTPOBAEM`, OLD.`ESTPOBAUS`, NOW(), OLD.`ESTPOBAIP`, OLD.`ESTPOBCOD`, OLD.`ESTPOBTOC`, OLD.`ESTPOBTRC`, OLD.`ESTPOBTSC`, OLD.`ESTPOBESC`, OLD.`ESTPOBPEC`, OLD.`ESTPOBCAN`, OLD.`ESTPOBPES`, OLD.`ESTPOBOBS`);

CREATE TRIGGER `ESTPOBINS` 
  AFTER INSERT ON `ESTPOB` 
  FOR EACH ROW 
    INSERT INTO `ESTPOBA` (`ESTPOBAMET`, `ESTPOBAEMP`, `ESTPOBAUSU`, `ESTPOBAFEC`, `ESTPOBADIP`, `ESTPOBACODNEW`, `ESTPOBATOCNEW`, `ESTPOBATRCNEW`, `ESTPOBATSCNEW`, `ESTPOBAESCNEW`, `ESTPOBAPECNEW`, `ESTPOBACANNEW`, `ESTPOBAPESNEW`, `ESTPOBAOBSNEW`)
    VALUES ('INSERT', NEW.`ESTPOBAEM`, NEW.`ESTPOBAUS`, NOW(), NEW.`ESTPOBAIP`, NEW.`ESTPOBCOD`, NEW.`ESTPOBTOC`, NEW.`ESTPOBTRC`, NEW.`ESTPOBTSC`, NEW.`ESTPOBESC`, NEW.`ESTPOBPEC`, NEW.`ESTPOBCAN`, NEW.`ESTPOBPES`, NEW.`ESTPOBOBS`);

CREATE TRIGGER `ESTPOBUPD` 
  AFTER UPDATE ON `ESTPOB` 
  FOR EACH ROW 
    INSERT INTO `ESTPOBA` (`ESTPOBAMET`, `ESTPOBAEMP`, `ESTPOBAUSU`, `ESTPOBAFEC`, `ESTPOBADIP`, `ESTPOBACODOLD`, `ESTPOBATOCOLD`, `ESTPOBATRCOLD`, `ESTPOBATSCOLD`, `ESTPOBAESCOLD`, `ESTPOBAPECOLD`, `ESTPOBACANOLD`, `ESTPOBAPESOLD`, `ESTPOBAOBSOLD`, `ESTPOBACODNEW`, `ESTPOBATOCNEW`, `ESTPOBATRCNEW`, `ESTPOBATSCNEW`, `ESTPOBAESCNEW`, `ESTPOBAPECNEW`, `ESTPOBACANNEW`, `ESTPOBAPESNEW`, `ESTPOBAOBSNEW`)
    VALUES ('UPDATE', NEW.`ESTPOBAEM`, NEW.`ESTPOBAUS`, NOW(), NEW.`ESTPOBAIP`, OLD.`ESTPOBCOD`, OLD.`ESTPOBTOC`, OLD.`ESTPOBTRC`, OLD.`ESTPOBTSC`, OLD.`ESTPOBESC`, OLD.`ESTPOBPEC`, OLD.`ESTPOBCAN`, OLD.`ESTPOBPES`, OLD.`ESTPOBOBS`, NEW.`ESTPOBCOD`, NEW.`ESTPOBTOC`, NEW.`ESTPOBTRC`, NEW.`ESTPOBTSC`, NEW.`ESTPOBESC`, NEW.`ESTPOBPEC`, NEW.`ESTPOBCAN`, NEW.`ESTPOBPES`, NEW.`ESTPOBOBS`);
