CREATE TABLE `ESTPER` (
    `ESTPERCOD` int(9) NOT NULL COMMENT 'CÓDIGO',
    `ESTPERECC` int(9) NOT NULL COMMENT 'ESTADO',
    `ESTPERTUC` int(9) NOT NULL COMMENT 'TIPO USUARIO',
    `ESTPERESC` int(9) NOT NULL COMMENT 'ESTABLECIMIENTO',
    `ESTPERPEC` int(9) NOT NULL COMMENT 'PERSONA',
    `ESTPEROBS` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN',
    `ESTPERAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
    `ESTPERAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
    `ESTPERAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
    `ESTPERAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ESTABLECIMIENTO PERSONA';

CREATE TABLE `ESTPERA` (
    `ESTPERACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `ESTPERAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `ESTPERAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
    `ESTPERAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `ESTPERAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `ESTPERADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `ESTPERACODOLD` int(9) NULL COMMENT 'CÓDIGO OLD',
    `ESTPERAECCOLD` int(9) NULL COMMENT 'ESTADO OLD',
    `ESTPERATUCOLD` int(9) NULL COMMENT 'TIPO USUARIO OLD',
    `ESTPERAESCOLD` int(9) NULL COMMENT 'ESTABLECIMIENTO OLD',
    `ESTPERAPECOLD` int(9) NULL COMMENT 'TIPO PERSONA OLD',
    `ESTPERAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN OLD',

    `ESTPERACODNEW` int(9) NULL COMMENT 'CÓDIGO NEW',
    `ESTPERAECCNEW` int(9) NULL COMMENT 'ESTADO NEW',
    `ESTPERATUCNEW` int(9) NULL COMMENT 'TIPO USUARIO NEW',
    `ESTPERAESCNEW` int(9) NULL COMMENT 'ESTABLECIMIENTO NEW',
    `ESTPERAPECNEW` int(9) NULL COMMENT 'TIPO PERSONA NEW',
    `ESTPERAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ESTABLECIMIENTO PERSONA AUDITORÍA';

ALTER TABLE `ESTPER` ADD PRIMARY KEY (`ESTPERCOD`);
ALTER TABLE `ESTPER` MODIFY `ESTPERCOD` int(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `ESTPER` ADD KEY `ESTPERECC` (`ESTPERECC`);
ALTER TABLE `ESTPER` ADD CONSTRAINT `FK_ESTPERECC` FOREIGN KEY (`ESTPERECC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);

ALTER TABLE `ESTPER` ADD KEY `ESTPERTUC` (`ESTPERTUC`);
ALTER TABLE `ESTPER` ADD CONSTRAINT `FK_ESTPERTUC` FOREIGN KEY (`ESTPERTUC`) REFERENCES `mayordomo_default`.`DOMFIC` (`DOMFICCOD`);

ALTER TABLE `ESTPER` ADD KEY `ESTPERESC` (`ESTPERESC`);
ALTER TABLE `ESTPER` ADD CONSTRAINT `FK_ESTPERESC` FOREIGN KEY (`ESTPERESC`) REFERENCES `mayordomo_default`.`ESTFIC` (`ESTFICCOD`);

ALTER TABLE `ESTPER` ADD KEY `ESTPERPEC` (`ESTPERPEC`);
ALTER TABLE `ESTPER` ADD CONSTRAINT `FK_ESTPERPEC` FOREIGN KEY (`ESTPERPEC`) REFERENCES `mayordomo_default`.`PERFIC` (`PERFICCOD`);

ALTER TABLE `ESTPERA` ADD PRIMARY KEY (`ESTPERACOD`);
ALTER TABLE `ESTPERA` MODIFY `ESTPERACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `ESTPERDLT` 
  BEFORE DELETE ON `ESTPER` 
  FOR EACH ROW 
    INSERT INTO `ESTPERA` (`ESTPERAMET`, `ESTPERAEMP`, `ESTPERAUSU`, `ESTPERAFEC`, `ESTPERADIP`, `ESTPERACODOLD`, `ESTPERAECCOLD`, `ESTPERATUCOLD`, `ESTPERAESCOLD`, `ESTPERAPECOLD`, `ESTPERAOBSOLD`)
    VALUES ('DELETE', OLD.`ESTPERAEM`, OLD.`ESTPERAUS`, NOW(), OLD.`ESTPERAIP`, OLD.`ESTPERCOD`, OLD.`ESTPERECC`, OLD.`ESTPERTUC`, OLD.`ESTPERESC`, OLD.`ESTPERPEC`, OLD.`ESTPEROBS`);

CREATE TRIGGER `ESTPERINS` 
  AFTER INSERT ON `ESTPER` 
  FOR EACH ROW 
    INSERT INTO `ESTPERA` (`ESTPERAMET`, `ESTPERAEMP`, `ESTPERAUSU`, `ESTPERAFEC`, `ESTPERADIP`, `ESTPERACODNEW`, `ESTPERAECCNEW`, `ESTPERATUCNEW`, `ESTPERAESCNEW`, `ESTPERAPECNEW`, `ESTPERAOBSNEW`)
    VALUES ('INSERT', NEW.`ESTPERAEM`, NEW.`ESTPERAUS`, NOW(), NEW.`ESTPERAIP`, NEW.`ESTPERCOD`, NEW.`ESTPERECC`, NEW.`ESTPERTUC`, NEW.`ESTPERESC`, NEW.`ESTPERPEC`, NEW.`ESTPEROBS`);

CREATE TRIGGER `ESTPERUPD` 
  AFTER UPDATE ON `ESTPER` 
  FOR EACH ROW 
    INSERT INTO `ESTPERA` (`ESTPERAMET`, `ESTPERAEMP`, `ESTPERAUSU`, `ESTPERAFEC`, `ESTPERADIP`, `ESTPERACODOLD`, `ESTPERAECCOLD`, `ESTPERATUCOLD`, `ESTPERAESCOLD`, `ESTPERAPECOLD`, `ESTPERAOBSOLD`, `ESTPERACODNEW`, `ESTPERAECCNEW`, `ESTPERATUCNEW`, `ESTPERAESCNEW`, `ESTPERAPECNEW`, `ESTPERAOBSNEW`)
    VALUES ('UPDATE', NEW.`ESTPERAEM`, NEW.`ESTPERAUS`, NOW(), NEW.`ESTPERAIP`, OLD.`ESTPERCOD`, OLD.`ESTPERECC`, OLD.`ESTPERTUC`, OLD.`ESTPERESC`, OLD.`ESTPERPEC`, OLD.`ESTPEROBS`, NEW.`ESTPERCOD`, NEW.`ESTPERECC`, NEW.`ESTPERTUC`, NEW.`ESTPERESC`, NEW.`ESTPERPEC`, NEW.`ESTPEROBS`);
