CREATE TABLE `ESTUBC` (
    `ESTUBCCOD` int(9) NOT NULL COMMENT 'CÓDIGO',
    `ESTUBCPOC` int(9) NOT NULL COMMENT 'POTRERO',
    `ESTUBCLOT` int(9) NOT NULL COMMENT 'LOTE',
    `ESTUBCESC` int(9) NOT NULL COMMENT 'ESTABLECIMIENTO',
    `ESTUBCNOM` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE',
    `ESTUBCOBS` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN',
    `ESTUBCAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
    `ESTUBCAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
    `ESTUBCAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
    `ESTUBCAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ESTABLECIMIENTO UBICACIÓN CABECERA';

CREATE TABLE `ESTUBCA` (
    `ESTUBCACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `ESTUBCAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `ESTUBCAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
    `ESTUBCAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `ESTUBCAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `ESTUBCADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `ESTUBCACODOLD` int(9) NULL COMMENT 'CÓDIGO OLD',
    `ESTUBCAPOCOLD` int(9) NULL COMMENT 'POTRERO OLD',
    `ESTUBCALOTOLD` int(9) NULL COMMENT 'LOTE OLD',
    `ESTUBCAESCOLD` int(9) NULL COMMENT 'ESTABLECIMIENTO OLD',
    `ESTUBCANOMOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE OLD',
    `ESTUBCAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN OLD',

    `ESTUBCACODNEW` int(9) NULL COMMENT 'CÓDIGO NEW',
    `ESTUBCAPOCNEW` int(9) NULL COMMENT 'POTRERO NEW',
    `ESTUBCALOTNEW` int(9) NULL COMMENT 'LOTE NEW',
    `ESTUBCAESCNEW` int(9) NULL COMMENT 'ESTABLECIMIENTO NEW',
    `ESTUBCANOMNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE NEW',
    `ESTUBCAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ESTABLECIMIENTO UBICACIÓN CABECERA AUDITORÍA';

ALTER TABLE `ESTUBC` ADD PRIMARY KEY (`ESTUBCCOD`);
ALTER TABLE `ESTUBC` MODIFY `ESTUBCCOD` int(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `ESTUBC` ADD KEY `ESTUBCPOC` (`ESTUBCPOC`);
ALTER TABLE `ESTUBC` ADD CONSTRAINT `FK_ESTUBCPOC` FOREIGN KEY (`ESTUBCPOC`) REFERENCES `mayordomo_default`.`ESTPOT` (`ESTPOTCOD`);

ALTER TABLE `ESTUBC` ADD KEY `ESTUBCLOT` (`ESTUBCLOT`);
ALTER TABLE `ESTUBC` ADD CONSTRAINT `FK_ESTUBCLOT` FOREIGN KEY (`ESTUBCLOT`) REFERENCES `mayordomo_establecimiento`.`ESTLOT` (`ESTLOTCOD`);

ALTER TABLE `ESTUBC` ADD KEY `ESTUBCESC` (`ESTUBCESC`);
ALTER TABLE `ESTUBC` ADD CONSTRAINT `FK_ESTUBCESC` FOREIGN KEY (`ESTUBCESC`) REFERENCES `mayordomo_default`.`ESTFIC` (`ESTFICCOD`);

ALTER TABLE `ESTUBCA` ADD PRIMARY KEY (`ESTUBCACOD`);
ALTER TABLE `ESTUBCA` MODIFY `ESTUBCACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `ESTUBCDLT` 
  BEFORE DELETE ON `ESTUBC` 
  FOR EACH ROW 
    INSERT INTO `ESTUBCA` (`ESTUBCAMET`, `ESTUBCAEMP`, `ESTUBCAUSU`, `ESTUBCAFEC`, `ESTUBCADIP`, `ESTUBCACODOLD`, `ESTUBCAPOCOLD`, `ESTUBCALOTOLD`, `ESTUBCAESCOLD`, `ESTUBCANOMOLD`, `ESTUBCAOBSOLD`)
    VALUES ('DELETE', OLD.`ESTUBCAEM`, OLD.`ESTUBCAUS`, NOW(), OLD.`ESTUBCAIP`, OLD.`ESTUBCCOD`, OLD.`ESTUBCPOC`, OLD.`ESTUBCLOT`, OLD.`ESTUBCESC`, OLD.`ESTUBCNOM`, OLD.`ESTUBCOBS`);

CREATE TRIGGER `ESTUBCINS` 
  AFTER INSERT ON `ESTUBC` 
  FOR EACH ROW 
    INSERT INTO `ESTUBCA` (`ESTUBCAMET`, `ESTUBCAEMP`, `ESTUBCAUSU`, `ESTUBCAFEC`, `ESTUBCADIP`, `ESTUBCACODNEW`, `ESTUBCAPOCNEW`, `ESTUBCALOTNEW`, `ESTUBCAESCNEW`, `ESTUBCANOMNEW`, `ESTUBCAOBSNEW`)
    VALUES ('INSERT', NEW.`ESTUBCAEM`, NEW.`ESTUBCAUS`, NOW(), NEW.`ESTUBCAIP`, NEW.`ESTUBCCOD`, NEW.`ESTUBCPOC`, NEW.`ESTUBCLOT`, NEW.`ESTUBCESC`, NEW.`ESTUBCNOM`, NEW.`ESTUBCOBS`);

CREATE TRIGGER `ESTUBCUPD` 
  AFTER UPDATE ON `ESTUBC` 
  FOR EACH ROW
    INSERT INTO `ESTUBCA` (`ESTUBCAMET`, `ESTUBCAEMP`, `ESTUBCAUSU`, `ESTUBCAFEC`, `ESTUBCADIP`, `ESTUBCACODOLD`, `ESTUBCAPOCOLD`, `ESTUBCALOTOLD`, `ESTUBCAESCOLD`, `ESTUBCANOMOLD`, `ESTUBCAOBSOLD`, `ESTUBCACODNEW`, `ESTUBCAPOCNEW`, `ESTUBCALOTNEW`, `ESTUBCAESCNEW`, `ESTUBCANOMNEW`, `ESTUBCAOBSNEW`)
    VALUES ('UPDATE', NEW.`ESTUBCAEM`, NEW.`ESTUBCAUS`, NOW(), NEW.`ESTUBCAIP`, OLD.`ESTUBCCOD`, OLD.`ESTUBCPOC`, OLD.`ESTUBCLOT`, OLD.`ESTUBCESC`, OLD.`ESTUBCNOM`, OLD.`ESTUBCOBS`, NEW.`ESTUBCCOD`, NEW.`ESTUBCPOC`, NEW.`ESTUBCLOT`, NEW.`ESTUBCESC`, NEW.`ESTUBCNOM`, NEW.`ESTUBCOBS`);