CREATE TABLE `ESTUBI` (
    `ESTUBICOD` int(9) NOT NULL COMMENT 'CÓDIGO',
    `ESTUBIPOC` int(9) NOT NULL COMMENT 'POTRERO',
    `ESTUBILOT` int(9) NOT NULL COMMENT 'LOTE',
    `ESTUBIESC` int(9) NOT NULL COMMENT 'ESTABLECIMIENTO',
    `ESTUBINOM` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE',
    `ESTUBIOBS` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN',
    `ESTUBIAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
    `ESTUBIAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
    `ESTUBIAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
    `ESTUBIAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ESTABLECIMIENTO UBICACIÓN';

CREATE TABLE `ESTUBIA` (
    `ESTUBIACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `ESTUBIAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `ESTUBIAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
    `ESTUBIAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `ESTUBIAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `ESTUBIADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `ESTUBIACODOLD` int(9) NULL COMMENT 'CÓDIGO OLD',
    `ESTUBIAPOCOLD` int(9) NULL COMMENT 'POTRERO OLD',
    `ESTUBIALOTOLD` int(9) NULL COMMENT 'LOTE OLD',
    `ESTUBIAESCOLD` int(9) NULL COMMENT 'ESTABLECIMIENTO OLD',
    `ESTUBIANOMOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE OLD',
    `ESTUBIAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN OLD',

    `ESTUBIACODNEW` int(9) NULL COMMENT 'CÓDIGO NEW',
    `ESTUBIAPOCNEW` int(9) NULL COMMENT 'POTRERO NEW',
    `ESTUBIALOTNEW` int(9) NULL COMMENT 'LOTE NEW',
    `ESTUBIAESCNEW` int(9) NULL COMMENT 'ESTABLECIMIENTO NEW',
    `ESTUBIANOMNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE NEW',
    `ESTUBIAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ESTABLECIMIENTO UBICACIÓN AUDITORÍA';

ALTER TABLE `ESTUBI` ADD PRIMARY KEY (`ESTUBICOD`);
ALTER TABLE `ESTUBI` MODIFY `ESTUBICOD` int(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `ESTUBI` ADD KEY `ESTUBIPOC` (`ESTUBIPOC`);
ALTER TABLE `ESTUBI` ADD CONSTRAINT `FK_ESTUBIPOC` FOREIGN KEY (`ESTUBIPOC`) REFERENCES `mayordomo_default`.`ESTPOT` (`ESTPOTCOD`);

ALTER TABLE `ESTUBI` ADD KEY `ESTUBILOT` (`ESTUBILOT`);
ALTER TABLE `ESTUBI` ADD CONSTRAINT `FK_ESTUBILOT` FOREIGN KEY (`ESTUBILOT`) REFERENCES `mayordomo_establecimiento`.`ESTLOT` (`ESTLOTCOD`);

ALTER TABLE `ESTUBI` ADD KEY `ESTUBIESC` (`ESTUBIESC`);
ALTER TABLE `ESTUBI` ADD CONSTRAINT `FK_ESTUBIESC` FOREIGN KEY (`ESTUBIESC`) REFERENCES `mayordomo_default`.`ESTFIC` (`ESTFICCOD`);

ALTER TABLE `ESTUBIA` ADD PRIMARY KEY (`ESTUBIACOD`);
ALTER TABLE `ESTUBIA` MODIFY `ESTUBIACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `ESTUBIDLT` 
  BEFORE DELETE ON `ESTUBI` 
  FOR EACH ROW 
    INSERT INTO `ESTUBIA` (`ESTUBIAMET`, `ESTUBIAEMP`, `ESTUBIAUSU`, `ESTUBIAFEC`, `ESTUBIADIP`, `ESTUBIACODOLD`, `ESTUBIAPOCOLD`, `ESTUBIALOTOLD`, `ESTUBIAESCOLD`, `ESTUBIANOMOLD`, `ESTUBIAOBSOLD`)
    VALUES ('DELETE', OLD.`ESTUBIAEM`, OLD.`ESTUBIAUS`, NOW(), OLD.`ESTUBIAIP`, OLD.`ESTUBICOD`, OLD.`ESTUBIPOC`, OLD.`ESTUBILOT`, OLD.`ESTUBIESC`, OLD.`ESTUBINOM`, OLD.`ESTUBIOBS`);

CREATE TRIGGER `ESTUBIINS` 
  AFTER INSERT ON `ESTUBI` 
  FOR EACH ROW 
    INSERT INTO `ESTUBIA` (`ESTUBIAMET`, `ESTUBIAEMP`, `ESTUBIAUSU`, `ESTUBIAFEC`, `ESTUBIADIP`, `ESTUBIACODNEW`, `ESTUBIAPOCNEW`, `ESTUBIALOTNEW`, `ESTUBIAESCNEW`, `ESTUBIANOMNEW`, `ESTUBIAOBSNEW`)
    VALUES ('INSERT', NEW.`ESTUBIAEM`, NEW.`ESTUBIAUS`, NOW(), NEW.`ESTUBIAIP`, NEW.`ESTUBICOD`, NEW.`ESTUBIPOC`, NEW.`ESTUBILOT`, NEW.`ESTUBIESC`, NEW.`ESTUBINOM`, NEW.`ESTUBIOBS`);

CREATE TRIGGER `ESTUBIUPD` 
  AFTER UPDATE ON `ESTUBI` 
  FOR EACH ROW
    INSERT INTO `ESTUBIA` (`ESTUBIAMET`, `ESTUBIAEMP`, `ESTUBIAUSU`, `ESTUBIAFEC`, `ESTUBIADIP`, `ESTUBIACODOLD`, `ESTUBIAPOCOLD`, `ESTUBIALOTOLD`, `ESTUBIAESCOLD`, `ESTUBIANOMOLD`, `ESTUBIAOBSOLD`, `ESTUBIACODNEW`, `ESTUBIAPOCNEW`, `ESTUBIALOTNEW`, `ESTUBIAESCNEW`, `ESTUBIANOMNEW`, `ESTUBIAOBSNEW`)
    VALUES ('UPDATE', NEW.`ESTUBIAEM`, NEW.`ESTUBIAUS`, NOW(), NEW.`ESTUBIAIP`, OLD.`ESTUBICOD`, OLD.`ESTUBIPOC`, OLD.`ESTUBILOT`, OLD.`ESTUBIESC`, OLD.`ESTUBINOM`, OLD.`ESTUBIOBS`, NEW.`ESTUBICOD`, NEW.`ESTUBIPOC`, NEW.`ESTUBILOT`, NEW.`ESTUBIESC`, NEW.`ESTUBINOM`, NEW.`ESTUBIOBS`);