CREATE TABLE `LOCDEP` (
  `LOCDEPCOD` int(6) NOT NULL COMMENT 'CÓDIGO',
  `LOCDEPEDC` int(9) NOT NULL COMMENT 'ESTADO',
  `LOCDEPPAC` int(3) NOT NULL COMMENT 'PAÍS',
  `LOCDEPNOM` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'NOMBRE',
  `LOCDEPOBS` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
  `LOCDEPAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
  `LOCDEPAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
  `LOCDEPAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
  `LOCDEPAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='DEPARTAMENTO';

CREATE TABLE `LOCDEPA` (
  `LOCDEPACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
  `LOCDEPAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
  `LOCDEPAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
  `LOCDEPAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
  `LOCDEPAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
  `LOCDEPADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',
  `LOCDEPACODOLD` int(6) NULL COMMENT 'CÓDIGO OLD',
  `LOCDEPAEDCOLD` int(9) NULL COMMENT 'ESTADO OLD',
  `LOCDEPAPACOLD` int(3) NULL COMMENT 'PAÍS OLD',
  `LOCDEPANOMOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE OLD',
  `LOCDEPAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN OLD',
  `LOCDEPACODNEW` int(6) NULL COMMENT 'CÓDIGO NEW',
  `LOCDEPAEDCNEW` int(9) NULL COMMENT 'ESTADO NEW',
  `LOCDEPAPACNEW` int(3) NULL COMMENT 'PAÍS NEW',
  `LOCDEPANOMNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE NEW',
  `LOCDEPAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='DEPARTAMENTO AUDITORÍA';

ALTER TABLE `LOCDEP` ADD PRIMARY KEY (`LOCDEPCOD`);
ALTER TABLE `LOCDEP` ADD KEY `LOCDEPEDC` (`LOCDEPEDC`);
ALTER TABLE `LOCDEP` ADD KEY `LOCDEPPAC` (`LOCDEPPAC`);
ALTER TABLE `LOCDEP` MODIFY `LOCDEPCOD` int(6) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;
ALTER TABLE `LOCDEP` ADD CONSTRAINT `FK_LOCDEPEDC` FOREIGN KEY (`LOCDEPEDC`) REFERENCES `DOMFIC` (`DOMFICCOD`);
ALTER TABLE `LOCDEP` ADD CONSTRAINT `FK_LOCDEPPAC` FOREIGN KEY (`LOCDEPPAC`) REFERENCES `LOCPAI` (`LOCPAICOD`);

ALTER TABLE `LOCDEPA` ADD PRIMARY KEY (`LOCDEPACOD`);
ALTER TABLE `LOCDEPA` MODIFY `LOCDEPACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `LOCDEPDLT` 
  BEFORE DELETE ON `LOCDEP` 
  FOR EACH ROW 
    INSERT INTO `LOCDEPA` (`LOCDEPAMET`, `LOCDEPAEMP`, `LOCDEPAUSU`, `LOCDEPAFEC`, `LOCDEPADIP`, `LOCDEPACODOLD`, `LOCDEPAEDCOLD`, `LOCDEPAPACOLD`, `LOCDEPANOMOLD`, `LOCDEPAOBSOLD`)
                  VALUES ('DELETE', OLD.`LOCDEPAEM`, OLD.`LOCDEPAUS`, NOW(), OLD.`LOCDEPAIP`, OLD.`LOCDEPCOD`, OLD.`LOCDEPEDC`, OLD.`LOCDEPPAC`, OLD.`LOCDEPNOM`, OLD.`LOCDEPOBS`);

CREATE TRIGGER `LOCDEPINS` 
  AFTER INSERT ON `LOCDEP` 
  FOR EACH ROW 
    INSERT INTO `LOCDEPA` (`LOCDEPAMET`, `LOCDEPAEMP`, `LOCDEPAUSU`, `LOCDEPAFEC`, `LOCDEPADIP`, `LOCDEPACODNEW`, `LOCDEPAEDCNEW`, `LOCDEPAPACNEW`, `LOCDEPANOMNEW`, `LOCDEPAOBSNEW`)
                  VALUES ('INSERT', NEW.`LOCDEPAEM`, NEW.`LOCDEPAUS`, NOW(), NEW.`LOCDEPAIP`, NEW.`LOCDEPCOD`, NEW.`LOCDEPEDC`, NEW.`LOCDEPPAC`, NEW.`LOCDEPNOM`, NEW.`LOCDEPOBS`);

CREATE TRIGGER `LOCDEPUPD` 
  AFTER UPDATE ON `LOCDEP` 
  FOR EACH ROW 
    INSERT INTO `LOCDEPA` (`LOCDEPAMET`, `LOCDEPAEMP`, `LOCDEPAUSU`, `LOCDEPAFEC`, `LOCDEPADIP`, `LOCDEPACODOLD`, `LOCDEPAEDCOLD`, `LOCDEPAPACOLD`, `LOCDEPANOMOLD`, `LOCDEPAOBSOLD`, `LOCPAIACODNEW`, `LOCPAIAEPCNEW`, `LOCPAIANOMNEW`, `LOCPAIAIC2NEW`, `LOCPAIAIC3NEW`)
                  VALUES ('UPDATE', NEW.`LOCDEPAEM`, NEW.`LOCDEPAUS`, NOW(), NEW.`LOCDEPAIP`, OLD.`LOCDEPCOD`, OLD.`LOCDEPEDC`, OLD.`LOCDEPPAC`, OLD.`LOCDEPNOM`, OLD.`LOCDEPOBS`, NEW.`LOCDEPCOD`, NEW.`LOCDEPEDC`, NEW.`LOCDEPPAC`, NEW.`LOCDEPNOM`, NEW.`LOCDEPOBS`);

INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'ALTO PARAGUAY', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'ALTO PARANÁ', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'AMAMBAY', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'BOQUERÓN', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'CAAGUAZÚ', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'CAAZAPÁ', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'CANINDEYÚ', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'CENTRAL', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'CONCEPCIÓN', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'CORDILLERA', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'GUAIRÁ', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'ITAPÚA', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'MISIONES', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'ÑEEMBUCÚ', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'PARAGUARÍ', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'PRESIDENTE HAYES', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
INSERT INTO `LOCDEP` (`LOCDEPEDC`, `LOCDEPPAC`, `LOCDEPNOM`, `LOCDEPOBS`, `LOCDEPAEM`, `LOCDEPAUS`, `LOCDEPAFH`, `LOCDEPAIP`) VALUES (1, 1, 'SAN PEDRO', NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');