CREATE TABLE `LOCPAI` (
  `LOCPAICOD` int(3) NOT NULL COMMENT 'CÓDIGO',
  `LOCPAIEPC` int(9) NOT NULL COMMENT 'ESTADO',
  `LOCPAINOM` varchar(100) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'NOMBRE',
  `LOCPAIIC2` char(2) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'ISO CHAR-2',
  `LOCPAIIC3` char(3) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'ISO CHAR-3',
  `LOCPAIIN3` int(3) NOT NULL COMMENT 'ISO NUMERO',
  `LOCPAIOBS` varchar(5120) CHARACTER SET utf8 COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
  `LOCPAIAEM` int(9) NOT NULL COMMENT 'AUDITORÍA EMPRESA',
  `LOCPAIAUS` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA USUARIO',
  `LOCPAIAFH` datetime NOT NULL COMMENT 'AUDITORÍA FECHA HORA',
  `LOCPAIAIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'AUDITORÍA IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='LOCALIDAD PAÍS';

CREATE TABLE `LOCPAIA` (
  `LOCPAIACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
  `LOCPAIAMET` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
  `LOCPAIAEMP` int(9) NOT NULL COMMENT 'EMPRESA',
  `LOCPAIAUSU` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
  `LOCPAIAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
  `LOCPAIADIP` char(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',
  `LOCPAIACODOLD` int(3) NULL COMMENT 'CÓDIGO OLD',
  `LOCPAIAEPCOLD` int(9) NULL COMMENT 'ESTADO OLD',
  `LOCPAIANOMOLD` varchar(100) CHARACTER SET utf8 COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE OLD',
  `LOCPAIAIC2OLD` char(2) CHARACTER SET utf8 COLLATE utf8_spanish_ci NULL COMMENT 'ISO CHAR-2 OLD',
  `LOCPAIAIC3OLD` char(3) CHARACTER SET utf8 COLLATE utf8_spanish_ci NULL COMMENT 'ISO CHAR-3 OLD',
  `LOCPAIAIN3OLD` int(3) NULL COMMENT 'ISO NUMERO OLD',
  `LOCPAIAOBSOLD` varchar(5120) CHARACTER SET utf8 COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN OLD',
  `LOCPAIACODNEW` int(3) NULL COMMENT 'CÓDIGO NEW',
  `LOCPAIAEPCNEW` int(9) NULL COMMENT 'ESTADO NEW',
  `LOCPAIANOMNEW` varchar(100) CHARACTER SET utf8 COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE NEW',
  `LOCPAIAIC2NEW` char(2) CHARACTER SET utf8 COLLATE utf8_spanish_ci NULL COMMENT 'ISO CHAR-2 NEW',
  `LOCPAIAIC3NEW` char(3) CHARACTER SET utf8 COLLATE utf8_spanish_ci NULL COMMENT 'ISO CHAR-3 NEW',
  `LOCPAIAIN3NEW` int(3) NULL COMMENT 'ISO NUMERO NEW',
  `LOCPAIAOBSNEW` varchar(5120) CHARACTER SET utf8 COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='LOCALIDAD PAÍS AUDITORÍA';

ALTER TABLE `LOCPAI` ADD PRIMARY KEY (`LOCPAICOD`);
ALTER TABLE `LOCPAI` ADD KEY `LOCPAIEPC` (`LOCPAIEPC`);
ALTER TABLE `LOCPAI` MODIFY `LOCPAICOD` int(3) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;
ALTER TABLE `LOCPAI` ADD CONSTRAINT `FK_LOCPAIEPC` FOREIGN KEY (`LOCPAIEPC`) REFERENCES `DOMFIC` (`DOMFICCOD`);

ALTER TABLE `LOCPAIA` ADD PRIMARY KEY (`LOCPAIACOD`);
ALTER TABLE `LOCPAIA` MODIFY `LOCPAIACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `LOCPAIDLT` 
  BEFORE DELETE ON `LOCPAI` 
  FOR EACH ROW 
    INSERT INTO `LOCPAIA` (`LOCPAIAMET`, `LOCPAIAEMP`, `LOCPAIAUSU`, `LOCPAIAFEC`, `LOCPAIADIP`, `LOCPAIACODOLD`, `LOCPAIAEPCOLD`, `LOCPAIANOMOLD`, `LOCPAIAIC2OLD`, `LOCPAIAIC3OLD`, `LOCPAIAIN3OLD`, `LOCPAIAOBSOLD`)
                  VALUES ('DELETE', OLD.`LOCPAIAEM`, OLD.`LOCPAIAUS`, NOW(), OLD.`LOCPAIAIP`, OLD.`LOCPAICOD`, OLD.`LOCPAIEPC`, OLD.`LOCPAINOM`, OLD.`LOCPAIIC2`, OLD.`LOCPAIIC3`, OLD.`LOCPAIIN3`, OLD.`LOCPAIOBS`);

CREATE TRIGGER `LOCPAIINS` 
  AFTER INSERT ON `LOCPAI` 
  FOR EACH ROW 
    INSERT INTO `LOCPAIA` (`LOCPAIAMET`, `LOCPAIAEMP`, `LOCPAIAUSU`, `LOCPAIAFEC`, `LOCPAIADIP`, `LOCPAIACODNEW`, `LOCPAIAEPCNEW`, `LOCPAIANOMNEW`, `LOCPAIAIC2NEW`, `LOCPAIAIC3NEW`, `LOCPAIAIN3NEW`, `LOCPAIAOBSNEW`)
                  VALUES ('INSERT', NEW.`LOCPAIAEM`, NEW.`LOCPAIAUS`, NOW(), NEW.`LOCPAIAIP`, NEW.`LOCPAICOD`, NEW.`LOCPAIEPC`, NEW.`LOCPAINOM`, NEW.`LOCPAIIC2`, NEW.`LOCPAIIC3`, NEW.`LOCPAIIN3`, NEW.`LOCPAIOBS`);

CREATE TRIGGER `LOCPAIUPD` 
  AFTER UPDATE ON `LOCPAI` 
  FOR EACH ROW 
    INSERT INTO `LOCPAIA` (`LOCPAIAMET`, `LOCPAIAEMP`, `LOCPAIAUSU`, `LOCPAIAFEC`, `LOCPAIADIP`, `LOCPAIACODOLD`, `LOCPAIAEPCOLD`, `LOCPAIANOMOLD`, `LOCPAIAIC2OLD`, `LOCPAIAIC3OLD`, `LOCPAIAIN3OLD`, `LOCPAIAOBSOLD`, `LOCPAIACODNEW`, `LOCPAIAEPCNEW`, `LOCPAIANOMNEW`, `LOCPAIAIC2NEW`, `LOCPAIAIC3NEW`, `LOCPAIAIN3NEW`, `LOCPAIAOBSNEW`)
                  VALUES ('UPDATE', NEW.`LOCPAIAEM`, NEW.`LOCPAIAUS`, NOW(), NEW.`LOCPAIAIP`, OLD.`LOCPAICOD`, OLD.`LOCPAIEPC`, OLD.`LOCPAINOM`, OLD.`LOCPAIIC2`, OLD.`LOCPAIIC3`, OLD.`LOCPAIIN3`, OLD.`LOCPAIOBS`, NEW.`LOCPAICOD`, NEW.`LOCPAIEPC`, NEW.`LOCPAINOM`, NEW.`LOCPAIIC2`, NEW.`LOCPAIIC3`, NEW.`LOCPAIIN3`, NEW.`LOCPAIOBS`);

INSERT INTO `LOCPAI` (`LOCPAIEPC`, `LOCPAINOM`, `LOCPAIIC2`, `LOCPAIIC3`, `LOCPAIIN3`, `LOCPAIOBS`, `LOCPAIAEM`, `LOCPAIAUS`, `LOCPAIAFH`, `LOCPAIAIP`) VALUES (1, 'PARAGUAY', 'PY', 'PRY', 600, NULL, 1, 'SISTEMA', NOW(), '127.1.1.1');
